### ISSUE TITLE
Can a email condition be set when added a contribution?

### ISSUE THREAD

**Issue by tapashdatta** [CiviCooP/org.civicoop.civirules#10]

**Comment by jaapjansma** [comment]
What do you mean with e-mail condition?

**Comment by tapashdatta** [comment]
Sorry,  I did not make it clear. I want to send an email notification to a leader when a certain type of contribution is made.

**Comment by jaapjansma** [comment]
Probably you can do that by combining the org.civicoop.emailapi extension and civirules extension. The e-mail api extension contains an action for the civirules engine. So that you could send e-mails.
I am not sure wether the right conditions are present in the civirules extension.

**Comment by tapashdatta** [comment]
Thanks, I tried that, but doesn't seem to have a condition for sending email when a contribution is added.

**Comment by jaapjansma** [comment]
Sending an e-mail is not a condition but an action

**Comment by tapashdatta** [comment]
My bad!!! yes, thats what I meant...

**Comment by jaapjansma** [comment]
Ok. Did you do a clear cache? e.g. http://yoursire/civicrm/clearcache?reset=1

**Comment by tapashdatta** [comment]
yes I did. I am not sure If I need to change any settings once the emailAPI is installed, because I do not see any UI changes.

**Comment by jaapjansma** [comment]
When did you install the email api? Could you do a git pull?

**Comment by tapashdatta** [comment]
I just did now when you asked me to...

**Comment by jaapjansma** [comment]
And the action send e-mail is not available in your civirules?

**Comment by tapashdatta** [comment]
Great!! it worked now after installing the master version from git hub. Previously I have installed direct from civicrm.

**Comment by tapashdatta** [comment]
Thanks :+1:

**Comment by tapashdatta** [comment]
But I do not get an option of who to send this email to? Only these 3 options
![untitled](https://cloud.githubusercontent.com/assets/5366545/8307956/c2d79de0-19b9-11e5-86c4-62eabee6243e.png)

**Comment by tapashdatta** [comment]
Sending an email to the contributor is already available directly from civicrm. But I want to send email to the manager.

**Comment by jaapjansma** [comment]
This not a standard action from send e-mail action. It could be developed quite easilty and I don't know if you have any development experiences or if you have any budget for this. (My estimate is that it is 1-2 hours of development)

**Comment by tapashdatta** [comment]
Unfortunately I do not have any dev experience. How much do you charge?

**Comment by jaapjansma** [comment]
We charge 80 euro per hour. If you want to have this developed send me a confirmation on jaap.jansma@civicoop.org with also the details for the invoice

**Comment by tapashdatta** [comment]
Thanks. I will speak to my manager and will get back to you.

**Comment by jaapjansma** [comment]
Have you spoken to your manager about this particular problem? Or could this issue be closed?

**Comment by tapashdatta** [comment]
@jaapjansma I really apologise for not being able to get back to you earlier on this. Yes, I am ok to go ahead with this improvement on civirules. But I would like couple more enhancement on this as well. Are you ok with that?

**Comment by jaapjansma** [comment]
Hey @tapashdatta great. Could you e-mail me with some more details. Probably we can arrange a skype call to discuss the details.

**Comment by jaapjansma** [comment]
This issue has been fixed
