### ISSUE TITLE
Compatibility with 4.5.8 version

### ISSUE THREAD

**Issue by dragonjon** [CiviCooP/org.civicoop.civirules#108]
civirules v3  is compatible with version 4.5 of CiviCRM??
In this page https://civicrm.org/extensions/civirules puts it only supports 4.4 and 4.6
Thanks

**Comment by ErikHommel** [comment]
We have tested it with 4.4 and 4.6, none of our customers that use CiviRules have been on 4.5. I do not know if others have tested it with 4.5, I would recommend you ask that question on StackExchange CiviCRM: http://civicrm.stackexchange.com/
