### ISSUE TITLE
New events required: when recurring contribution added/changed/deleted

### ISSUE THREAD

**Issue by ErikHommel** [CiviCooP/org.civicoop.civirules#11]
New events are required around recurring contributions

**Comment by ErikHommel** [comment]
@jaapjansma the recurring contribution is no entity in the post hook. Could we do it the other way around: add an execution of rules (with entity recurring contribution) to the maf.no.recurring extension? It would then be a MAF Norge specific thing, but there is no escaping that. If so, can you pick up this issue?

**Comment by jaapjansma** [comment]
This works out of the box. But the customisations for the MAF in the extension no.maf.recurring did not work the standard civicrm BAO.
