### ISSUE TITLE
Event tokens aren't being processed in CiviRules SMS messages

### ISSUE THREAD

**Issue by termdark** [CiviCooP/org.civicoop.civirules#111]
From: http://civicrm.stackexchange.com/questions/15245/sending-sms-on-event-registration/ 

I have set up a new rule, with the trigger as a new event registration, and I have set the action to be 'Send SMS'.

I have set up a message template and used the following event tokens

> You've been registered for {event.title}, starting at {event.start_date}. More info: {event.info_url}

When users receive the SMS, the tokens aren't replaced with the relevant information.

Would anyone be able to help?
Thanks

**Comment by ErikHommel** [comment]
First, this issue belongs with the SMS API, not here (https://github.com/CiviCooP/org.civicoop.smsapi).

No action in 2 years, if the issue is still valid and you would like to either work on it yourself or fund our work on it, you should register the issue in the SMS API repo.
