### ISSUE TITLE
Entity in CRM_Civirules_Config in function getValidTriggerOperations should be based on table

### ISSUE THREAD

**Issue by ErikHommel** [CiviCooP/org.civicoop.civirules#115]
Is now hardcoded in function. Should also have option to add entitties (for example PUM Case Project)

**Comment by jaapjansma** [comment]
Fixed this to load the entity types from civicrm core. Custom extensions such as PUM Case project could let civicrm know what entities they have with the hook civicrm_entityTypes, see: https://docs.civicrm.org/dev/en/latest/hooks/hook_civicrm_entityTypes/
