### ISSUE TITLE
Delete CiviRules extension files, then try to disable any extension

### ISSUE THREAD

**Issue by JohnFF** [CiviCooP/org.civicoop.civirules#117]
Exception: "API error: API (CiviRuleCondition, create) does not exist (join the API team and implement it!)"
#0 /srv/www/exttest/sites/all/modules/civicrm/CRM/Core/ManagedEntities.php(292): CRM_Core_ManagedEntities->onApiError("CiviRuleCondition", "create", (Array:3), (Array:5))
#1 /srv/www/exttest/sites/all/modules/civicrm/CRM/Core/ManagedEntities.php(196): CRM_Core_ManagedEntities->disableEntity(Object(CRM_Core_DAO_Managed))
#2 /srv/www/exttest/sites/all/modules/civicrm/CRM/Core/ManagedEntities.php(123): CRM_Core_ManagedEntities->reconcileDisabledModules()
#3 /srv/www/exttest/sites/all/modules/civicrm/CRM/Core/Invoke.php(398): CRM_Core_ManagedEntities->reconcile()
#4 /srv/www/exttest/sites/all/modules/civicrm/CRM/Extension/Manager.php(342): CRM_Core_Invoke::rebuildMenuAndCaches(TRUE)
#5 /srv/www/exttest/sites/all/modules/civicrm/CRM/Admin/Form/Extensions.php(198): CRM_Extension_Manager->disable((Array:1))
#6 /srv/www/exttest/sites/all/modules/civicrm/CRM/Core/Form.php(431): CRM_Admin_Form_Extensions->postProcess()
#7 /srv/www/exttest/sites/all/modules/civicrm/CRM/Core/StateMachine.php(160): CRM_Core_Form->mainProcess()
#8 /srv/www/exttest/sites/all/modules/civicrm/CRM/Core/QuickForm/Action/Next.php(61): CRM_Core_StateMachine->perform(Object(CRM_Admin_Form_Extensions), "next", "Next")

**Comment by gareth-circle** [comment]
Hi John,

I had a similar issue with a client who had just uninstalled CiviRules.

After some investigation I found a fix can be achieved by clearing out the civirules entries in the civicrm_managed database table.

This is what worked for me, please check this suits you first though:

`DELETE FROM civicrm_managed WHERE module = 'org.civicoop.civirules';`

If you were using the emailapi extension the same issue will occur, so if you have removed that extension you should consider something like this as well:

`DELETE FROM civicrm_managed WHERE module = 'org.civicoop.emailapi';`

CiviCooP Team - Could something along the lines of this SQL be added to the uninstall script of the civirules and emailapi extension?

Thanks,

Gareth
