### ISSUE TITLE
Issue running all scheduled Jobs after upgraded to civirule 1.8

### ISSUE THREAD

**Issue by yosefromano** [CiviCooP/org.civicoop.civirules#120]
I get a "http Error 500" when clicking the " run all scheduled jobs manually" link on the scheduled jobs page. 
This happens only after updating the database for the new version of civirule 1.8

I am using civicrm 4.6.19

**Comment by yosefromano** [comment]
I found this error msg: Fatal error: Can't use method return value in write context in .../code/sites/all/extensions/org.civicoop.civirules-1.3/CRM/Civirules/Engine.php on line 282

**Comment by jaapjansma** [comment]
I cannot really tell what is going wrong. But I get the impression it is something to do with your specific setup. One you can do to see whether this is in the setup of one of your rules is try to disable all of them and then run the cron job. When the cron job process successfully it is one of your rules causing this. The you could try enable one-by-one and see on which one the cron job fails.

**Comment by yosefromano** [comment]
@jaapjansma , thank you for the quick reply. 
This happened on 2 different environments with different rules. 
I don't think it is a particular rule that is causing this issue. 
Can you see if it happens on your environment? 
Go to System Settings > Scheduled Jobs  and try to click on the  " run all scheduled jobs manually" link at the top of the page.

**Comment by jaapjansma** [comment]
@yosefromano I dont have any issues with CiviRules Cron jobs. I have an active 4.7 installation. Its very strange.

**Comment by yosefromano** [comment]
Hum... Strange I am using 4.6
I reverted to the previous version of civirules and it works

**Comment by catorghans** [comment]
I have the same error in CiviRules 1.12 and CiviCRM 4.6
php -l sites/all/libraries/civiextensions/org.civicoop.civirules/CRM/Civirules/Engine.php
PHP Fatal error:  Can't use method return value in write context in sites/all/libraries/civiextensions/org.civicoop.civirules/CRM/Civirules/Engine.php on line 282

I see this site has php 5.3.3, so my guess is that is the problem, will do a php upgrade.

**Comment by jaapjansma** [comment]
I assume that the error is fixed in the meantime and will close the issue.
