### ISSUE TITLE
Should we replace the requiredEntities with doesWorkWithTrigger

### ISSUE THREAD

**Issue by ErikHommel** [CiviCooP/org.civicoop.civirules#122]
In the current engine there are to parts that check if a condition/trigger combination works (on the condition level):

1. the required entities that are added in the function requiredEntities
2. the entities that are checked in the optional function doesWorkWithTrigger

I now have a user story where a condition can be applicable to more entities. As at the moment the required entities are checked before the function doesWorkWithTrigger, I can not add the condition as ONE of the required entities is present but not ALL.

Workaround used now: create two conditions (one for each entity).
Ideally we should revisit this conceptually and decide if it needs any action or if the workaround is actually the one to instruct

**Comment by jaapjansma** [comment]
I have refactored all conditions to use the doesWorkWithTrigger function instead of the requiredEntities. I have also updated the documentation.
