### ISSUE TITLE
4.6 domain version check isn't multisite aware

### ISSUE THREAD

**Issue by josephlacey** [CiviCooP/org.civicoop.civirules#123]
The changes on this commit, https://github.com/CiviCooP/org.civicoop.civirules/commit/46f5dbd64acf082213a3d266032925fbc71658ba#diff-e5590222e13e1d7d3e3589f64b3485db, assumes CiviCRM is running only a single domain.  When running multiple domains, the Administer > CiviRules page to create new rules returns 'Expected one Domain but found X,' where X is the number of domains configured.  This check should be changed to account for multisite instances.

I'll submit a PR for the fix I've made, which uses get instead of getvalue, and assumes that the version associated with domain 1 is sufficient for this check.  There might be a more elegant fix that pulls the current domain of the user and then checks that domain's version, but I doubt that the other domains will have different versions.

**Comment by josephlacey** [comment]
Looks like checking for the current domain is built into the API already.  I've fixed the patch, so it only adds a parameter to the API request for the current domain.

**Comment by jaapjansma** [comment]
Thanks @josephlacey
