### ISSUE TITLE
Works with 4.7 but not in info.xml

### ISSUE THREAD

**Issue by JohnFF** [CiviCooP/org.civicoop.civirules#131]
This doesn't appear in the extensions section for 4.7. A shame, as it's a handy bit of kit! @jaapjansma

**Comment by RandyTobias** [comment]
I noticed this as well. Well, I haven't installed it yet. but I see that release 1.9 explicitly states that it was made to work with 4.7. Does someone need to submit a PR to get the info.xml updated?

**Comment by jaapjansma** [comment]
@JohnFF and @RandyTobias you are right the info.xml is not update. Feel free to update it and do a pull request.
