### ISSUE TITLE
FieldValueChangeComparison Civirule Condition - Form display is awkward on update

### ISSUE THREAD

**Issue by Vgratioulet** [CiviCooP/org.civicoop.civirules#136]
When creating a new rule and adding a FieldValueChangeComparison condition, the form is displayed nicely with JQuery that handles the fields and field options.

But when the rule is created and we come back to add a FieldValueChangeComparison condition, the form is awkward, the JQuery isn't called.

I think it is linked to the fact that in the first case, it is in the same page, and in the second case, the form is displayed in an overlay.

A workaround is to create the condition without changing anything on the form, and then come back to the rule, right click on 'edit condition' and select 'open in new tab', that will open the condition form in the page and not in a overlay, and the form is nicely displayed.

An example can be made with a rule on 'Activity changed' and a condition on 'Compare old activity status to new activity status'

**Comment by jaapjansma** [comment]
I just checked this in the current civirules version and to me the form looks the same when adding the condition as on updating the condition. I will close this issue.
