### ISSUE TITLE
Trashing and Restoring a Contact fire 'update' $op and update 'is_deleted' field

### ISSUE THREAD

**Issue by Vgratioulet** [CiviCooP/org.civicoop.civirules#138]
There are triggers for Trashing and Restoring Contacts on the $op 'trash' and 'restore',
but when trashing or restoring a Contact, the $op is 'update' and the field 'is_deleted' is updated to 0 (for restore) or 1 (for trash)

**Comment by kainuk** [comment]
Triggers react now on the $op update. The effect is that on the standard interface action and the api delete action the triggers is fired. However it is not fired yet on a api update of the is_delete field.

**Comment by kainuk** [comment]
Added the simulated trash and restore
