### ISSUE TITLE
Warnings on upgrade

### ISSUE THREAD

**Issue by JohnFF** [CiviCooP/org.civicoop.civirules#141]
On clicking the upgrade to version 1.12, many many warning along the line of the following:

Warning: unlink(/var/www/master/sites/default/files/civicrm/ext/org.civicoop.civirules/psr/log/LogLevel.php): Permission denied in CRM_Utils_File::cleanDir() (line 156 of /var/www/master/sites/all/modules/civicrm/CRM/Utils/File.php).
Warning: unlink(/var/www/master/sites/default/files/civicrm/ext/org.civicoop.civirules/psr/log/LoggerInterface.php): Permission denied in CRM_Utils_File::cleanDir() (line 156 of /var/www/master/sites/all/modules/civicrm/CRM/Utils/File.php).
Warning: rmdir(/var/www/master/sites/default/files/civicrm/ext/org.civicoop.civirules/psr/log): Permission denied in CRM_Utils_File::cleanDir() (line 165 of /var/www/master/sites/all/modules/civicrm/CRM/Utils/File.php).
Warning: rmdir(/var/www/master/sites/default/files/civicrm/ext/org.civicoop.civirules/psr): Permission denied in CRM_Utils_File::cleanDir() (line 165 of /var/www/master/sites/all/modules/civicrm/CRM/Utils/File.php).
Warning: unlink(/var/www/master/sites/default/files/civicrm/ext/org.civicoop.civirules/civirules.php): Permission denied in CRM_Utils_File::cleanDir() (line 156 of /var/www/master/sites/all/modules/civicrm/CRM/Utils/File.php).
Warning: unlink(/var/www/master/sites/default/files/civicrm/ext/org.civicoop.civirules/CRM/CivirulesConditions/Email/PrimaryEmailChanged.php): Permission denied in CRM_Utils_File::cleanDir() (line 156 of /var/www/master/sites/all/modules/civicrm/CRM/Utils/File.php).

**Comment by jaapjansma** [comment]
This looks more like you have something wrong with your file permissions in CiviCRM. I am not aware that we clean any directories in CiviRules and this code seems to do that.

**Comment by ErikHommel** [comment]
Closing the issue as there are no other instances of problems reported and CiviRuls does not clean any directories.
