### ISSUE TITLE
'No delay' actions are not performed.

### ISSUE THREAD

**Issue by khorporative** [CiviCooP/org.civicoop.civirules#143]
I have installed CiviRules on CiviCRM 4.7.14. I tried to create a few simple test rules, but none of them worked. I suspect I might have to look for solution somewhere else.

```
Trigger: Contribution is changed 
Linked Condition: Contact in group TEST
Linked Action: Remove contact from group: TEST
```

I also tried a few similar Rules, e.g.:
```
IF Contribution is added THEN remove Contact from Group.
IF Tag is added THEN remove from Group.
IF contact is removed from group THEN display the Message.
IF Action is added THEN remove Contact from specific Group. (w/o Condition)
```
All were set to run with NO DELAY.

What might have gone wrong? Any hints where to look for solution?

**Comment by jaapjansma** [comment]
@khorporative thanks for the message. First of all I don't realy like the tone of the message. I am not a supplier and I am reacting to your message in my spare time. So putting Immediate in capitals won't make any difference.

I am not sure what might have gone wrong. It looks like the remove contact from group is not working. Could you try a different action?

**Comment by khorporative** [comment]
I am sorry, it was meant the type of action - immediate vs. delayed. I will fix the topic name.

**Comment by ErikHommel** [comment]
I suggest you read our documentation on https://wiki.civicrm.org/confluence/display/CRMDOC/CiviRules+Cookbook? That should help you along your way. And if you do run into any questions, can we ask you to put them on StackExchange (https://civicrm.stackexchange.com/) first? Then you reach out to more people able to help you and you share the solutions. Thanks for reporting!

**Comment by khorporative** [comment]
@ErikHommel Thank you, Erik! 

I've read the documentation to the best of my understanding. Also the interface of CiviRules seems pretty straight-forward to me.

In fact, I did write to StackExchange before writing here:
https://civicrm.stackexchange.com/questions/18279/how-to-troubleshoot-civirules-triggers

**Comment by ErikHommel** [comment]
Agree about the pretty straight forward @khorporative :-) I have just answered your Stack Exchange posting, CiviRules seems to work on my local 4.7.15 install. Let us continue on SE!

**Comment by jaapjansma** [comment]
@khorporative apologies for misunderstanding the topic title

**Comment by ErikHommel** [comment]
Closed, new issue for Remove Contact From Group created
