### ISSUE TITLE
Rule Organisation added trigger based on condition Civirules 1.13 CiviCRM 4.6

### ISSUE THREAD

**Issue by chris-bird-coolearth** [CiviCooP/org.civicoop.civirules#145]
We were having the issue with the organisation added trigger, a rule set up to change an organizations subtype to business wasn't triggering based on a field value comparison. 
For example:
![image](https://cloud.githubusercontent.com/assets/25900175/25475207/e6a03296-2b2d-11e7-965d-40de72d459a8.png)
It seems that because the entity is organization, the function getEntityData() was returning an empty array meaning the $isValid check was false.

My solution (maybe a bit hacky but it works!)

File: /org.civicoop.civirules/CRM/Civirules/TriggerData/TriggerData.php:85:
public function getEntityData($entity) {
    //only lookup entities by their lower case name. Entity is now case insensetive
    if (isset($this->entity_data[strtolower($entity)]) && is_array($this->entity_data[strtolower($entity)])) {
      return $this->entity_data[strtolower($entity)];
    //just for backwards compatibility also check case sensitive entity
    } elseif (isset($this->entity_data[$entity]) && is_array($this->entity_data[$entity])) {
      return $this->entity_data[$entity];
    } elseif (strtolower($entity) == strtolower('Contact') && $this->getContactId() **|| strtolower($entity) == strtolower('Organization') && $this->getContactId()**) {
      $contactObject = new CRM_Contact_BAO_Contact();
      $contactObject->id = $this->getContactId();
      $contactData = array();
      if ($contactObject->find(true)) {
        CRM_Core_DAO::storeValues($contactObject, $contactData);
      }
      return $contactData;
    }
    return array();
  }
Hopefully if anyone else runs into this it might help

**Comment by ErikHommel** [comment]
Thanks for the contribution @chris-bird-coolearth
