### ISSUE TITLE
source_contact_id is not a valid integer

### ISSUE THREAD

**Issue by chris-bird-coolearth** [CiviCooP/org.civicoop.civirules#152]
We have a rule in which when someone signs up for the newsletter, it creates an activity on the newly created contact with newsletter sign up - completed

However, if this rule is enabled, and the user signing up is not logged in then it goes white screen and says "source_contact_id is not a valid integer", if you're logged in, it works great... 

I've had to add in a quick fix by adding
       if(!is_user_logged_in()){
            $parameters["source_contact_id"]=1;
        }
before the api call (this is for wordpress)

I'm not sure if this is unique to us or is repeatable but worth letting you know, there might be an option already to solve this that I'm not aware of!

**Comment by jaapjansma** [comment]
@chris-bird-coolearth Thank for reporting this issue. I am not sure the function is_user_logged_in() is unique over all CMSes... 
What would be even better is to given an option to the user in the setup screen of the action to set it to the logged in user or to set it to a pre-selected contact.

**Comment by chris-bird-coolearth** [comment]
It's not over all cms's I'm sure you could check to see current_user_id then set it, my background is in wordpress so I know my way around it!

I definitely agree with that, I needed to get a fix up quick... I'll get on adding that and share it when done (if I don't get too bogged down)

**Comment by PalanteJon** [comment]
The second answer on this question should provide a CMS-agnostic solution, if I'm understanding the problem correctly: https://civicrm.stackexchange.com/a/3841/12
