### ISSUE TITLE
SMS conversation integration / adding new triggers and actions

### ISSUE THREAD

**Issue by michaelmcandrew** [CiviCooP/org.civicoop.civirules#159]
Hi all,

We are wrapping up a new [SMS conversation extension](https://github.com/3sd/civicrm-sms-conversations) that allows you to do surveys etc. via SMS. Part of the spec was the ability to have user initiated conversations, e.g. where someone texts 'help' to a number to start a conversation and we decided to integrate with CiviRules to provide this.

In order to do so, I created a new condition that matches based on activity details and an action that allows you to start an sms conversation. I also created an action which starts an SMS conversation.

This was my first foray into CiviRules. I liked it! And of course, the nice thing about integrating with CiviRules is that they get all the other triggers for free.

I presume that you will want the activity details filter. But I am not sure if you want the scheduled SMS conversation action in CiviRules or if there is another way I should be implementing it.

So I thought I'd wait for a little bit of feedback from you before creating the PR.

Here is the branch on my repo in case you want to have a look@:
https://github.com/michaelmcandrew/org.civicoop.civirules/tree/sms-conversation

A couple of extra bits of info in case you are interested: 

* the worflow that allows the conversing to happen is seperate from CiviRules. We probably could have implemented it via CiviRules but at the same time it is fairly domain specific to SMS and so we decided to keep it seperate.
* We might want to add another filter to CiviRules so we can trigger other actions as part of a conversation (e.g. schedule a phone call if someone says that they would like to talk in more detail with someone as part of a text message e.g (reply 'chat' if you'd like someone to call you to discuss your needs in more detail).

**Comment by jaapjansma** [comment]
@michaelmcandrew we have created civirules in such a way that actions and conditions and triggers could be located in other extensions. For example: org.civicoop.emailapi contains an send e-mail action for civirules. 

So it would be great that the actions/conditions belonging to the sms conversation extension are located inside that extensions. The more generic ones you could submit them to civirules with a PR.

**Comment by michaelmcandrew** [comment]
thanks for the link @jaapjansma - I had a look for some documentation to work that out but couldn't find any but I am sure I'll be able to work it out from looking at that example.

I'll add the specific ones to SMS conversation extension and submit the generic ones as a PR as you suggest.
