### ISSUE TITLE
Error when submitting donation online using Paypal Pro

### ISSUE THREAD

**Issue by tapashdatta** [CiviCooP/org.civicoop.civirules#16]
![untitled](https://cloud.githubusercontent.com/assets/5366545/8388730/c975b5f0-1c5d-11e5-8da5-eee27768ef27.png)

Using civicrm 4.6.4. Although civirules works in the backend perfectly.

**Comment by ErikHommel** [comment]
@tapashdatta it would really help us if you could tell us what you were doing when this happened, and a backtrace of the error. If you do not know how to get a backtrace, go to Administer/System Settings/Debugging and Error Handling and tick the box at 'Display Backtrace'.
![schermafdruk van 2015-06-27 14 50 37](https://cloud.githubusercontent.com/assets/458090/8392041/e49773b8-1cdb-11e5-9f2b-a9b46ae1ea3f.png)

I expect though the error is not about CiviRules, there are no profiles in CiviRules.

**Comment by tapashdatta** [comment]
Hi, Erik

CiviCRM_API3_Exception: "Expected one Profile but found 0"

#0 /www/demo/sites/all/modules/civicrm_custom_scripts/civicrm_extensions/org.civicoop.civirules-master/CRM/Civirules/Utils/PreData.php(47): civicrm_api3("Profile", "getsingle", (Array:1))
#1 /www/demo/sites/all/modules/civicrm_custom_scripts/civicrm_extensions/org.civicoop.civirules-master/civirules.php(126): CRM_Civirules_Utils_PreData::pre("edit", "Profile", "1502", (Array:51))
#2 /www/demo/sites/all/modules/civicrm/CRM/Utils/Hook.php(215): civirules_civicrm_pre("edit", "Profile", "1502", (Array:51))
#3 /www/demo/sites/all/modules/civicrm/CRM/Utils/Hook/DrupalBase.php(87): CRM_Utils_Hook->runHooks((Array:47), "civicrm_pre", 4, "edit", "Profile", "1502", (Array:51), NULL, NULL)
#4 /www/demo/sites/all/modules/civicrm/CRM/Utils/Hook.php(282): CRM_Utils_Hook_DrupalBase->invoke(4, "edit", "Profile", "1502", (Array:51), NULL, NULL, "civicrm_pre")
#5 /www/demo/sites/all/modules/civicrm/CRM/Contact/BAO/Contact.php(1869): CRM_Utils_Hook::pre("edit", "Profile", "1502", (Array:51))
#6 /www/demo/sites/all/modules/civicrm/CRM/Contribute/Form/Contribution/Confirm.php(870): CRM_Contact_BAO_Contact::createProfileContact((Array:51), (Array:16), "1502", (Array:0), NULL, NULL, TRUE)
#7 /www/demo/sites/all/modules/civicrm/CRM/Core/Form.php(345): CRM_Contribute_Form_Contribution_Confirm->postProcess()
#8 /www/demo/sites/all/modules/civicrm/CRM/Core/StateMachine.php(164): CRM_Core_Form->mainProcess()
#9 /www/demo/sites/all/modules/civicrm/CRM/Core/QuickForm/Action/Next.php(61): CRM_Core_StateMachine->perform(Object(CRM_Contribute_Form_Contribution_Confirm), "next", "Next")
#10 /www/demo/sites/all/modules/civicrm/packages/HTML/QuickForm/Controller.php(203): CRM_Core_QuickForm_Action_Next->perform(Object(CRM_Contribute_Form_Contribution_Confirm), "next")
#11 /www/demo/sites/all/modules/civicrm/packages/HTML/QuickForm/Page.php(103): HTML_QuickForm_Controller->handle(Object(CRM_Contribute_Form_Contribution_Confirm), "next")
#12 /www/demo/sites/all/modules/civicrm/CRM/Core/Controller.php(353): HTML_QuickForm_Page->handle("next")
#13 /www/demo/sites/all/modules/civicrm/CRM/Core/Invoke.php(312): CRM_Core_Controller->run((Array:3), NULL)
#14 /www/demo/sites/all/modules/civicrm/CRM/Core/Invoke.php(86): CRM_Core_Invoke::runItem((Array:15))
#15 /www/demo/sites/all/modules/civicrm/CRM/Core/Invoke.php(54): CRM_Core_Invoke::_invoke((Array:3))
#16 /www/demo/sites/all/modules/civicrm/drupal/civicrm.module(489): CRM_Core_Invoke::invoke((Array:3))
#17 [internal function](): civicrm_invoke("contribute", "transact")
#18 /www/demo/includes/menu.inc(519): call_user_func_array("civicrm_invoke", (Array:2))
#19 /www/demo/index.php(21): menu_execute_active_handler()
#20 {main}

**Comment by ErikHommel** [comment]
@tapashdatta  
This seems to suggest that there is a problem related to the Contribution Page:
    /www/demo/sites/all/modules/civicrm/CRM/Contribute/Form/Contribution/Confirm.php(870): CRM_Contact_BAO_Contact::createProfileContact((Array:51), (Array:16), "1502", (Array:0), NULL, NULL, TRUE)

It could certainly be a bug that only occurs if the mailing group is linked to a contribution page. Can you please retest adding it to a mailing group without the Contribution Page stuff and see what happens then?

**Comment by tapashdatta** [comment]
You are right!! If Top of the page profile is active, payment goes thru fine, But if there are 2 profile both top and bottom i am getting this error.

**Comment by ErikHommel** [comment]
@jaapjansma I assume there is a bug in the GroupContact Add action. Is it a 5 min job or does it require more effort?

**Comment by jaapjansma** [comment]
@tapashdatta  Could you send us a screenshot of the rule you have setup? And the backtrace seem to suggest you are doing an action with profiles.

@ErikHommel I cannot conclude yet wether it is a 5 minute job or not. Because I cannot conclude this I do think it requires more effort.

**Comment by ErikHommel** [comment]
@jaapjansma I am happy either way :-) But make sure you check with @tapashdatta if he wants to spend any money on this if it gets too much

**Comment by tapashdatta** [comment]
![untitled](https://cloud.githubusercontent.com/assets/5366545/8406034/a9a97550-1e50-11e5-8975-65718e768997.png)
here is the screenshot

**Comment by jaapjansma** [comment]
@tapashdatta and could you explain how I could reproduce this error?

**Comment by tapashdatta** [comment]
I am using paypal web pro on a contribution page. Have 2 profile on top primary address. 2nd Contribution notes. 
Thats all!!!

**Comment by tapashdatta** [comment]
Another point to note, as soon as I disabled the extension my payments were going thru successfully.

**Comment by jaapjansma** [comment]
@tapashdatta thanks. Could you lookup under the Administer --> Customise data and screens --> Profiles the ID of the profiles you have been using. I want to verify that ID 1502 is an profile ID and not an contact id. If ID 1502 is not an id of a profile

**Comment by jaapjansma** [comment]
I have just done a test drive of donating anonmously on my local site. And it works. So it could be that is something in your local setup with your profile set up

**Comment by tapashdatta** [comment]
1502 seems a contact ID and not profile ID. 
TBH, I dont know what is happening. I have 2 site setup and both of them had same issue. Anyways, never mind, i guess I have to live without civicrules. Thanks for help..

**Comment by jaapjansma** [comment]
well the problem is that I am not able to reproduce this on my local civicrm install. And I need to reproduce this in a local install to fix it

**Comment by jaapjansma** [comment]
Could you try to test this in your install with the latest civirules module? I might have found the issue.

**Comment by tapashdatta** [comment]
@jaapjansma it works now with the latest changes. Thanks!!!
