### ISSUE TITLE
Questionable silent exit from the code

### ISSUE THREAD

**Issue by michaelmcandrew** [CiviCooP/org.civicoop.civirules#161]
In this file https://github.com/CiviCooP/org.civicoop.civirules/commit/364857c131499423bc2f13e307b9c242fbbe4d81#diff-aa891eeb11e8574a68c555b5bff26895
there is an echo and exit from the code which looks a bit wrong since it silently stops code execution on a failed action thus hiding useful debugging info from the developer. In my instance I was calling it via a webhook and did not have access to what the script was echoing.

It seems a bit wrong for a hook to stop execution of the entire script with an exit and also looked odd as it rendered the rest of that function unreachable.

**Comment by jaapjansma** [comment]
Aih that exit shouldn't be there.

**Comment by michaelmcandrew** [comment]
Thanks for fixing so quickly.
