### ISSUE TITLE
Send email removes unsubscribe token

### ISSUE THREAD

**Issue by ErikHommel** [CiviCooP/org.civicoop.civirules#163]
Spotted on Stack Exchange:

https://civicrm.stackexchange.com/questions/20506/email-sent-via-civirules-removes-unsubscribe-token-from-email-template

**Comment by jaapjansma** [comment]
The problem with the `{action.optOutUrl}` token is that generates a url which is linked to a send mass mailing. 

When CiviRules sends an e-mail it is not a mass mailing but an inidvidual one. Send to one specific contact at the time.
