### ISSUE TITLE
DB Error: no such field", -19, 16, (Array:2), "\nINSERT INTO civicrm_prevnext_cache

### ISSUE THREAD

**Issue by KarinG** [CiviCooP/org.civicoop.civirules#181]
Goedenmiddag! We're getting [on a 4.7 project; they are using CiviRules quite a bit now] a number of:

`#2 /var/www/civicrm/4.7/packages/DB.php(985): PEAR_Error->__construct("DB Error: no such field", -19, 16, (Array:2), "\nINSERT INTO civicrm_prevnext_cache ( entity_table, entity_id1, entity_id2, ...")`

invoked via:
`#29 /var/www/drupal/git-7/includes/menu.inc(527): civicrm_invoke("contact", "search", "custom")`

At first I told them to stop using Custom Search! But we tracked it down to: CiviRules -> Find Rules:
`/civicrm/contact/search/custom?reset=1&csid=16`

So the issue appears to be how CiviRules implements the custom search.

**Comment by ErikHommel** [comment]
I expect to be able to have a first look on 13 Feb.

**Comment by KarinG** [comment]
Thanks Erik!

**Comment by jaapjansma** [comment]
This sounds like the same issue as #195 and an issue in core: https://github.com/civicrm/civicrm-core/pull/11829

**Comment by KarinG** [comment]
Ha! We found it first 😀

**Comment by jaapjansma** [comment]
:D this one is fixed in CiviCRM core. Will close it.

**Comment by KarinG** [comment]
Prima!
