### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by KarinG** [CiviCooP/org.civicoop.civirules#182]
I've got a client who would like to be able to cc and bcc a via CiviRules generated Welcome message to a New Member; much like to you can do with native CiviCRM Contribution Thank you receipting and native CiviCRM Event confirmation receipting. Wondering if that has been on your radar at all - and/or if you know of anyone else looking for this.

**Comment by ErikHommel** [comment]
@KarinG Not that I am aware of. But I reckon it would be relatively straightforward, what do you think @jaapjansma ?

**Comment by jaapjansma** [comment]
It sounds straightforward. 

The action for sending an email is in the email api extension. It might be that the cc and bcc also need to be implemented in the API.

**Comment by ErikHommel** [comment]
That was my thought to @jaapjansma. Reckon you would be able to have a quick look sometime?

**Comment by jaapjansma** [comment]
I just had a look and indeed we need to implement the API with cc and bcc and then add it to the action. I might have some time for that during this Brussels Sprint.

**Comment by jaapjansma** [comment]
@KarinG I had some time to fix this tonight.
