### ISSUE TITLE
Default api query does not retrieve more than 25 relatonships

### ISSUE THREAD

**Issue by eyeonall** [CiviCooP/org.civicoop.civirules#186]
I have an instance with more than 25 relationships. The default api query when setting a condition on relationship type only pulls the first 25. It is an easy fix. Sorry if the format is off, not really experienced with this whole patch thing.. 

```
===================================================================

--- org.civicoop.civirules/CRM/CivirulesConditions/Relationship/RelationshipType.php
+++ org.civicoop.civirules/CRM/CivirulesConditions/Relationship/RelationshipType.php
@@ -89,7 +89,7 @@

   public static function getRelationshipTypes() {
     $return = array();
-    $relationshipTypes = civicrm_api3('RelationshipType', 'Get', array('is_active' => 1));
+    $relationshipTypes = civicrm_api3('RelationshipType', 'Get', array('is_active' => 1, 'options' => array('limit' => 0),));
     foreach ($relationshipTypes['values'] as $relationshipType) {
       $return[$relationshipType['id']] = $relationshipType['label_a_b'].' - '.$relationshipType['label_b_a'];
     }
```

**Comment by jaapjansma** [comment]
@eyeonall  Thanks for your fix. I have put your fix in the code.

Usually when you want to fix something your create a fork (a copy on your own github page) of the repository. You then do the fix there and then you create a Pull Request (PR). Anyway thanks for your contribution.

**Comment by eyeonall** [comment]
I apologize. This is the first time I formally contributed and was 
concerned I might mess something up. I will try it that way should 
something else come up.



------ Original Message ------
