### ISSUE TITLE
Delayed actions recheck activity conditions using old data

### ISSUE THREAD

**Issue by DanielvV** [CiviCooP/org.civicoop.civirules#193]
**executeDelayedAction() function**

`$processAction = self::areConditionsValid($actionEngine->getTriggerData());`

The whole activity (with old data) is there in an unserialized object from the queue.
[CRM/Civirules/Engine.php#L138](https://github.com/CiviCooP/org.civicoop.civirules/blob/master/CRM/Civirules/Engine.php#L138)

**example isConditionValid() function**

`$activity = $triggerData->getEntityData('Activity');`

[CRM/CivirulesConditions/Activity/Status.php#L40](https://github.com/CiviCooP/org.civicoop.civirules/blob/master/CRM/CivirulesConditions/Activity/Status.php#L40)

**workaround / fix for specific example**
```
    $activityData = $triggerData->getEntityData('Activity');

    $activity = civicrm_api3('Activity', 'getsingle', array(
      'return' => array("status_id"),
      'id' => $activityData['id'],
    ));
```

**Comment by jaapjansma** [comment]
@DanielvV could you submit a PR with the fix?

**Comment by DanielvV** [comment]
This is not an isolated problem. Should this be fixed in the separate conditions (triggers api requests, also when not needed when not delayed).
Or fix it in the engine?

**Comment by jaapjansma** [comment]
Oh I thought it was an isolated problem. I am not sure about whether it is really a problem. In my understanding one would like to check the conditions with the data passed to the trigger. Most conditions look things up in the database rather than using the data from the trigger. So I would leave this up to the condition to decide whether one might use data from the trigger or from the database.

**Comment by DanielvV** [comment]
I think that most triggers, if not all, should use the database when rechecking the conditions after the delay.

**Comment by jaapjansma** [comment]
Yes I think that most conditions should do that but that all depends on the condition (for example there is a condition compare changed fields; that trigger is only going to work with the data present in the trigger and not in the database.

**Comment by DanielvV** [comment]
In that case there are three points when checking after the delay:
Trigger: change activity
1: before change (triggerdata)
2: after change (triggerdata)
3: after delay (database)

When rechecking after the delay I think 1 and 3 need to be compared.
Not 1 and 2.

2 and 3 should be the same when there is no delay.

**Comment by jaapjansma** [comment]
Yes you are right but that should be done in the condition. The condition knows where it wants to have the data from.

**Comment by jaapjansma** [comment]
What I am trying to say is that not the engine is broken. The engine provides the data to the condition and actions. That should be intact it is up to to condition and action to decide whether they want to use the data provided by the trigger or the data in the database.

**Comment by DanielvV** [comment]
So all conditions should get their data from the database. Otherwise rechecking doesn't have any effect.

I don't see any usercase for a condition that uses old data when rechecking after delay. Do you have an example?

Checking a condition without delay will not be impacted, as the data from the trigger is the same as the database.

I still think that using the engine to update the triggerdata after the delay is the best solution.

**Comment by jaapjansma** [comment]
I dont agree because the triggerData class holds the data used at the moment the trigger is fired. That is a conceptual thought and messing that up makes the engine messy.

**Comment by DanielvV** [comment]
Then another solution:
Only provide id's in the triggerdata.
Then conditions are forced to get the data from the database.

Otherwise conditions that use triggerdata don't support rechecking...

**Comment by DanielvV** [comment]
1 every condition should support rechecking after delay
2 using triggerdata (old data) as new data breaks rechecking functionality
3 rechecking only needs an id for new data (data before change should stay in triggerdata, only needed for change-triggers)

or

1 every condition should support rechecking after delay
2 using triggerdata (old data) as new data breaks rechecking functionality
3 if triggerdata will be updated after delay triggerdata can be used for rechecking

**Comment by jaapjansma** [comment]
I will go for option 1 and that one is already working as the id is already present in the trigger data.

**Comment by DanielvV** [comment]
Ok. I will create a PR.

**Comment by DanielvV** [comment]
@jaapjansma 
Other issues:
- if the activity (or any other entity) is deleted within the time of the delay, the action will still run.
- if the ActivityContact is changed within the time of the delay, the Action will still use the old ActivityContact

This PR only fixes the problem for activity conditions.

A lot of other conditions still use old data.
Examples:
[Case/](https://github.com/CiviCooP/org.civicoop.civirules/tree/master/CRM/CivirulesConditions/Case) (most of them), [Contact/SubtypesChanged.php](https://github.com/CiviCooP/org.civicoop.civirules/blob/master/CRM/CivirulesConditions/Contact/SubtypesChanged.php) and [Contact/BirthdayChanged.php](https://github.com/CiviCooP/org.civicoop.civirules/blob/master/CRM/CivirulesConditions/Contact/BirthdayChanged.php).

**Comment by jaapjansma** [comment]
Thanks! I have added a comment in the PR. Could you have a look at it and explain what you think should happen?

**Comment by DanielvV** [comment]
I don't see a comment in the PR...

**Comment by jaapjansma** [comment]
See: https://github.com/CiviCooP/org.civicoop.civirules/pull/194/files#diff-1fed27f2edf26ba82262ae2b3be03fd8L32

**Comment by DanielvV** [comment]
Nothing there...

**Comment by jaapjansma** [comment]
Excuses I had to submit the comment

**Comment by DanielvV** [comment]
Now I see it :)

**Comment by jaapjansma** [comment]
Thanks for your PR @DanielvV !

**Comment by DanielvV** [comment]
np :)

@jaapjansma should I create issues for:
1. Action should not run after delay if entity is deleted
2. Action should use new data after delay if rechecking is enabled
3. All conditions should use new data after delay

**Comment by jaapjansma** [comment]
Yes you can do so.

**Comment by jaapjansma** [comment]
@DanielvV there was an issue with the execution of action in version 1.18 (see #191). I do think I have fixed that issue but it might had some influences on this issue as well (maybe those two issues are related). Could you check out the master version and test it?
