### ISSUE TITLE
Field Changed condition will trigger if field is not submitted/changed

### ISSUE THREAD

**Issue by eyeonall** [CiviCooP/org.civicoop.civirules#196]
I created two field changed conditions based off of your Birthday has changed condition. Basically copied it and renamed the classes etc.. Deceased state changed and Deceased date changed conditions. The issue holds true with the birthday conditions so I will use that.

To Reproduce: 
1. Set a contact changed trigger with the birthday change condition.
2. Set an action of add activity to target ( makes it easy to see if if triggered )
3. Go to a contact page of a contact with a birthday that is already set and click on a section like the employer/job section. Anything but the demographics section where the birthday is updated. No need to change anything, just click 'Save'.

The activity will be generated. 

The issue is with the getFieldData function of the CRM_CivirulesConditions_Generic_FieldChanged abstract class. When submitting a change in a subset of contact fields that do not include the field being evaluated, the getFieldData will return 'null' since the field is not in the $data associative array. However, since the birthday is set, the field comparison of the isConditionValid will return true because the field data is null but the original data has the birthdate.

I have a fix for it so I have forked the repo, will commit the change, and issue a pull request. However, if I do something wrong ( this will be the first time I have ever done a pull request ), I will put my fix here:

in the FieldChanged.php:
after 
```
if ($entity != $triggerData->getOriginalEntity()) {
      return false;
    }
```
line 45 add:
```
    // we need to check to see if the data being submitted actually contains the field we are comparing. if not, return false, no change
    if ( ! array_key_exists($this->getField(), $triggerData->getEntityData($entity)) ) {
      return false;
    } 
```
Th fix seems like it may be too simple but it works, at least for the basic use cases.

Hope this helps.
A.J.

**Comment by jaapjansma** [comment]
Closed in PR #197
