### ISSUE TITLE
Notices with group action

### ISSUE THREAD

**Issue by ErikHommel** [CiviCooP/org.civicoop.civirules#2]
Notice: Undefined property: CRM_CivirulesActions_GroupContact_Form_GroupId::$condition in CRM_CivirulesActions_Form_Form->postProcess() (line 78 of /var/www/localmaf/sites/default/civicrm_extensions/org.civicoop.civirules/CRM/CivirulesActions/Form/Form.php).
    Notice: Trying to get property of non-object in CRM_CivirulesActions_Form_Form->postProcess() (line 78 of /var/www/localmaf/sites/default/civicrm_extensions/org.civicoop.civirules/CRM/CivirulesActions/Form/Form.php).

**Comment by jaapjansma** [comment]
Hoi @ErikHommel,

Wat was je aan het doen toen deze notice optrad?

Jaap

**Comment by ErikHommel** [comment]
Op donderdag 21 mei 2015 heeft Jaap Jansma <notifications@github.com> het
volgende geschreven:

> Hoi @ErikHommel <https://github.com/ErikHommel>,
>
> Wat was je aan het doen toen deze notice optrad?
>
> Jaap
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/CiviCooP/org.civicoop.civirules/issues/2#issuecomment-104314732>
> .
>


-- 


Met vriendelijke groet,
Erik Hommel

T.   06 30 05 40 96
M. hommel@ee-atwork.nl

* <http://api.twitter.com/ehommel63>*   *
<http://nl.linkedin.com/in/erikhommel>*

**Comment by jaapjansma** [comment]
Zelfde als issue #21
