### ISSUE TITLE
Action should not run after delay if entity is deleted

### ISSUE THREAD

**Issue by adanielvv** [CiviCooP/org.civicoop.civirules#200]
**Example**
_Example rule_
Trigger: Contribution is added
Action: Add activity to contact
Delay by 1 minutes
Unchecked: Don't recheck condition upon processing of delayed action

_Replicate_
1. Create the above example rule
2. Create a contribution
3. Remove the contribution
4. After a minute: run the job _Process delayed civirule actions_

_Result_
Activity is created

_Expected result IMHO_
If rechecking is enabled (this case):
Activity is not created

If rechecking is disabled:
Activity is created

**Comment by ErikHommel** [comment]
See answer to #202
