### ISSUE TITLE
Updating a custom field with the API does not present itself in original data for field change comparison

### ISSUE THREAD

**Issue by eyeonall** [CiviCooP/org.civicoop.civirules#204]
I created a few field change classes for custom data that worked fine when updating from the contact screen but not when the update was handled via the API. For whatever reason, the 'custom_' was not present in the entity data or the original data. However, the update was available in the $trigger->custom_values however the original data still did not contain the custom fields. 

I am going to submit a pull request with the changes made primarily for review. The changes include updating the PreData to populate the latest custom field values and add them to to the original data and an extra method to list all custom fields from the trigger::custom_values array.

I dont believe that all of them are necessary and I dont know exactly how to handle multi-valued custom fields. I am just hoping that the changes are such that they get you most of the way and save you some work.

Also, it turns out that the 'entity' returned was not consistently lower case.

A.J.

**Comment by jaapjansma** [comment]
Thanks!
