### ISSUE TITLE
deleting custom data record throws errors

### ISSUE THREAD

**Issue by lcdservices** [CiviCooP/org.civicoop.civirules#208]
To reproduce:

- create a custom data set for contacts that supports multiple records
- create a rule that triggers on custom data changing
- add a record to that custom data set for a contact
- delete the record
- observe the logs

This returns the error: "Expected one Contact but found 25"
Traced to CRM/CivirulesPostTrigger/ContactCustomDataChanged.php where there is an api call to contacts getsingle. The issue is that when the custom data record is deleted, there is no remaining entity_id with which to retrieve the contact, and so no id is passed to the getsingle call.

**Comment by lcdservices** [comment]
https://github.com/CiviCooP/org.civicoop.civirules/pull/209

This just makes sure we have an entity ID before we try to call contact.getsingle. However, I think it may deserve a broader look. Actually, I feel like the entity ID should be passed to the custom hook, even on delete, so that may be an issue in core. But as it currently stands, there is potentially a gap here, since you can't really trigger on custom data deletions when using multi-record type sets.

**Comment by jaapjansma** [comment]
This definilty needs some broader look. And I agree that the entity ID should have been passed to the custom hook but that it is indeed a fix in core.

**Comment by jaapjansma** [comment]
I will close this issue, as I have created a Hack around this issue and I have created an CiviCRM core issue with a proposed fix.

**Comment by jaapjansma** [comment]
The bug is also fixed in CiviCRM core.
