### ISSUE TITLE
Only tags from main Tag Set available for Contact is tagged

### ISSUE THREAD

**Issue by magnolia61** [CiviCooP/org.civicoop.civirules#214]
No funds to support this, do have time to test, but mainly as a placeholder I tought i'd report:
Only tags from main Tag Set available for "Contact is tagged",
so tags from additional Tag Sets are not available to be chosen.
These are available for the "Tag is" condition though, so solution must be close around some corner ;-)

**Comment by jaapjansma** [comment]
I have tested this in the latest CiviRules version and it seems to work. So I will close this issue.
