### ISSUE TITLE
adding tag to contact that already has the tag should not cause an error

### ISSUE THREAD

**Issue by jmcclelland** [CiviCooP/org.civicoop.civirules#215]
We have a rule that adds a tag to a contact when they register for a particular event.

The first time the rule triggers it works fine.

However, the second time it triggers, CiviRules throws an error since the tag has already been added. The error percolates up through the stack causing unpredictable problems along the way (the particular error we received was a constraint violation adding custom data to a participant record - the constraint violation was caused by trying to add data to the custom_value table using a participant id that no longer exists because it was deleted during an roll back operation triggered by the civirules failure).

I think that the correct fix would be to check if the tag exists on the contact before trying to add it. Or, somehow catching the error that it already exists.

**Comment by jaapjansma** [comment]
The correct fix is indeed check whether the tag already exists. There is already a condition contact has tag adding that condition would probably fix your problem.
