### ISSUE TITLE
New condition for activity dates

### ISSUE THREAD

**Issue by ahillio** [CiviCooP/org.civicoop.civirules#236]
In rules that deal with activities, it would be awesome to have the activity's date available in a condition.

For example, we'd like to be able to create a rule that: checks the date and if the date is in the future set the status to be "scheduled", and another rule to check the date and if it's now or in the past then set the status to "completed".

Awesome contribution to Civi and Open Source!  Thanks!!!

**Comment by ErikHommel** [comment]
Makes sense. Are you able to fund or develop yourself?
By the way, the repository has moved to https://lab.civicrm.org/extensions/civirules

**Comment by eyeonall** [comment]
I know the repo has been moved but this ticket is here so I am not entirely sure where to respond. I actually created a condition for that exact scenario last week in a custom extension for a client. I will look at adding it as a civirules condition

**Comment by ErikHommel** [comment]
That would be great @eyeonall

**Comment by eyeonall** [comment]
Gotta love the nuances of a new system. I registered with CiviCRM, the 
account was approved, however, when I go to the civirules gitlab link 
and try to log in I got a 404 telling me that I do not have permission 
to view it. Tried to log in again, this time to the home page, was 
allowed to log in and had to browse to the project.

I forked the project and will upload the conditions after I update to 
2.1 and make sure they still work.


------ Original Message ------

**Comment by jaapjansma** [comment]
I have merged your changes on gitlab.

**Comment by eyeonall** [comment]
Glad to be of assistance. I just realized I forgot to pull out the 
author information. The organization I wrote the conditions for has a 
good deal of controversy around it so you might want to pull it out.



------ Original Message ------

**Comment by jaapjansma** [comment]
@eyeonall feel free to provide another Merge Request on gitlab to remove the author from the source. If not I am happy to leave it there.

**Comment by eyeonall** [comment]
I am fine with it. I was talking to a buddy of mine who was stationed in 
Germany and he mentioned the mixed feeling you folks across the pond 
have. So I offered. Contribution, not pride and ownership, is the 
motivating factor for me.

Out of curiosity, I have written a handful of very specific conditions 
that still use the requiredEntities and MGD files. Will the upgrade to 
2.x require me to refactor?

------ Original Message ------

**Comment by jaapjansma** [comment]
The 'old way' still works. The requiredEntities method and the MGD files still work. But it is preferable to not use them.
