### ISSUE TITLE
contact tokens do not appear in emails sent by civirules

### ISSUE THREAD

**Issue by mol3earth** [CiviCooP/org.civicoop.civirules#242]
civicrm 4.6.38
civirules 2.2

This worked in civicrm 4.6.34 for us, but after upgrading this stopped working

contact tokens do not work 
e.g. {$contact.contact_id} , {$contact.email_greeting}

event tokens do get passed though and work.
e.g.  {$event.event_id}

**Comment by jaapjansma** [comment]
So I will close this issue as we should discus this issue on lab.civicrm.org or on the e-mail extension.
