### ISSUE TITLE
Request: Migrate docs/issues to github or civicrm wiki

### ISSUE THREAD

**Issue by shawnholt** [CiviCooP/org.civicoop.civirules#29]
I'm sure you are more comfortable in  redmine but it would be great to have everything in github or civicrm.org if possible.  (note - i think there are some github/redmine sync tools too.) Actually, I think this is really a management /consistency issue for all civicrm extensions...

Note,  I see several references:
http://wiki.civicrm.org/confluence/display/CRM/CiviRules+extension redirects to ...
http://redmine.civicoop.org/projects/civirules/wiki
https://github.com/CiviCooP/org.civicoop.civirules
https://civicrm.org/extensions/civirules
https://civicrm.org/blogs/erikhommel/extension-civirules-now-avaible-download-live-showcase-maf-norge

**Comment by ErikHommel** [comment]
We started on the CiviCRM wiki. The reason it is not maintained on the CiviCRM wiki is that it was down a number of times when we needed it, so we switched to Redmine. It could be moved over to GitHub if anyone is happy to take that on.

Verstuurd vanaf mijn iPad

Op 8 jul. 2015 om 19:43 heeft shawnholt <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


I'm sure you are more comfortable in redmine but it would be great to have everything in github or civicrm.org<http://civicrm.org> if possible. (note - i think there are some github/redmine sync tools too.) Actually, I think this is really a management /consistency issue for all civicrm extensions...

Note, I see several references:
http://wiki.civicrm.org/confluence/display/CRM/CiviRules+extension redirects to ...
http://redmine.civicoop.org/projects/civirules/wiki
https://github.com/CiviCooP/org.civicoop.civirules
https://civicrm.org/extensions/civirules
https://civicrm.org/blogs/erikhommel/extension-civirules-now-avaible-download-live-showcase-maf-norge

**Comment by ErikHommel** [comment]
I have moved the documentation to the CiviCRM wiki:
http://wiki.civicrm.org/confluence/display/CRMDOC/CiviRules+-+how+to+make+your+own
http://wiki.civicrm.org/confluence/display/CRMDOC/CiviRules+Cookbook
