### ISSUE TITLE
4.5/4.6 compatibility?

### ISSUE THREAD

**Issue by magnolia61** [CiviCooP/org.civicoop.civirules#3]
Are there plans to make the extension compatible with the current stable version of civicrm (4.6)?

**Comment by ErikHommel** [comment]
There is currently no customer of ours that needs this or wants to fund this. As soon as there is, we will certainly make it compatible. If another community member comes across this as an issue, I am sure they will :-)
Do you need it to be compatible with 4.6 and are you willing and able to fund it?

**Comment by magnolia61** [comment]
Clear :-) Also wanted to file this issue as a placeholder.
The other way around: do you know of any incompatibilities?
I can test it with 4.6 and help debugging. Unfortunately I can only offer
no funding, but I can offer my time :-)

**Comment by ErikHommel** [comment]
Good to have it as a placeholder! I do not expect too many issues using it with 4.6, but would be really nice if you can test?

**Comment by shawnholt** [comment]
@magnolia61 I'd like to use this with civicrm 4.6.4 on a production wordpress site (or will have to go with drupal/rules)  happy to help test too if you are working on it.

**Comment by joemcl** [comment]
Hey @magnolia61 or @shawnholt , have you come across any issues when testing the extension on 4.6?

**Comment by shawnholt** [comment]
I ran into an issue #30 and imagine it is related to the version since you can't add any activities.

**Comment by PalanteJon** [comment]
I was able to create a simple rule on CiviCRM master (updated through today) - see screenshot for the exact rule.  So I think it's safe to say that CiviRules as a framework works generally, but individual actions/conditions may not.
![selection_062](https://cloud.githubusercontent.com/assets/1796012/9738149/34e008a6-5618-11e5-9c81-7b57e5ee1215.jpg)

**Comment by jaapjansma** [comment]
I know from a few installations which are running on 4.6. As @PalanteJon points out it doesn't say anything if individual conditions or actions are working on 4.6
