### ISSUE TITLE
Adding activity creates error

### ISSUE THREAD

**Issue by shawnholt** [CiviCooP/org.civicoop.civirules#30]
testing Master on 4.6.4 / wordpress.
Create a rule to add an activity when contribution is added.  getting error:
Fatal error: Class 'CRM_Contact_Form_NewContact' not found in /home/xxxx/public_html/wp-content/plugins/files/civicrm/extensions/org.civicoop.civirules/CRM/CivirulesActions/Activity/Form/Activity.php on line 32

I also found these with debug on:
Notice: Undefined index: activity_type_id in /home/xxxxx/public_html/wp-content/plugins/files/civicrm/extensions/org.civicoop.civirules/CRM/CivirulesActions/Activity/Add.php on line 55

Notice: Undefined index: status_id in /home/xxxxx/public_html/wp-content/plugins/files/civicrm/extensions/org.civicoop.civirules/CRM/CivirulesActions/Activity/Add.php on line 57

Notice: Undefined index: subject in /home/xxxxx/public_html/wp-content/plugins/files/civicrm/extensions/org.civicoop.civirules/CRM/CivirulesActions/Activity/Add.php on line 60

**Comment by jaapjansma** [comment]
@shawnholt we have done lots of work since 9th of july on Civirules. All on behalve of our clients and during the Edale Sprint. Probably the latest code might solve this issue

**Comment by shawnholt** [comment]
ok. likely fixed but sorry don't have a stack for testing at the moment but will review when i do.

**Comment by redmeades** [comment]
I am seeing this on civi 4.6.10 with master downloaded on 2015-11-10.

The action is created, but the form to edit the parameters fails to render.

![screen shot 2015-11-12 at 9 29 55 am](https://cloud.githubusercontent.com/assets/4978837/11104943/04368366-8920-11e5-80e7-dc0e9b566442.png)

**Comment by alejandro-ixiam** [comment]
@jaapjansma we are testing civirules 1.2 in Civi 4.6 (Great Job!!!) and the activity error is still happening.
After selecting the Add Action, and 

Add Activity to contact, we go to a site error message (/site-error). The activity is created with without parameters.

**Comment by ErikHommel** [comment]
@alejandro-ixiam we got some funding for testing with 4.6, and plan to do this in the first week of December. This error will certainly be part of that work, unless someone else has been kind enough to find the error and fix it :+1:

**Comment by jaapjansma** [comment]
@alejandro-ixiam could you provide a screenshot of the error message? Thanks

**Comment by alejandro-ixiam** [comment]
@ErikHommel , great!!! we are planning to spend time with CiviRules, we find it very helpful for some of our projects. We are happy to getting involved in one way (funding) or another (working) :+1:

**Comment by alejandro-ixiam** [comment]
![captura de pantalla 2015-11-20 13 30 43](https://cloud.githubusercontent.com/assets/11352292/11300277/f758144c-8f8d-11e5-9f26-67d8b3b9137a.png)

![captura de pantalla 2015-11-20 13 31 44](https://cloud.githubusercontent.com/assets/11352292/11300281/02a0bad4-8f8e-11e5-8259-a1be4cfa68af.png)

**Comment by ErikHommel** [comment]
Linked to issue #50 ?

**Comment by jaapjansma** [comment]
The error was caused by the the new functionality around contact ref fields in CiviCRM.
