### ISSUE TITLE
enhancement request: compare custom fields

### ISSUE THREAD

**Issue by shawnholt** [CiviCooP/org.civicoop.civirules#31]
When I try to compare values I cannot see custom fields for that value.  I assume that is expected behavior.  

BTW here is the usecase (http://civicrm.stackexchange.com/questions/3716/allowing-multiple-fianancial-types-for-same-price-set-single-contribution-page): Set the financial type for a priceset based on a field.

1.   Create a contribution record using a temporary financial type (e.g. general donation)
2.   Create a custom field for the financial type (e.g. medical fund, orphan fund)
3.   Trigger rule when submitting new contribution
4.   Create condition (perhaps based on page, etc.)
5.   Action is to set the financial type based on the custom field

**Comment by jaapjansma** [comment]
Hey Shawnholt, this should be possible with the latest Civirules code. I had to fix this for a civicrm install I manage myself.
