### ISSUE TITLE
Create and Implement logging class

### ISSUE THREAD

**Issue by ErikHommel** [CiviCooP/org.civicoop.civirules#37]
There is a civirule log table, perhaps we should also add a log (text) file logging the performed actions and warnings. For example, the Set Thank You Date action for Contribution could have an error resulting from an API call. Now I assume we do not want to add a new Exception for this as it is not exactly vital to daily processing, but we would want to log a warning so someone could check this?
What do you think @jaapjansma?

**Comment by jaapjansma** [comment]
Yes that could be very usefull. But we should make it as such that the logfile makes sense. And we should define what we should log and what not

**Comment by ErikHommel** [comment]
Agree in principle. However, we should create a separate class that makes this possible, add some logging which we think makes sense. What is added is then up to the developer adding the condition/action. Perhaps something for the Edale sprint :-)

**Comment by jaapjansma** [comment]
Agree. Should we create an issue list for the Edale sprint?

**Comment by ErikHommel** [comment]
I see you have already added the milestone :-). Good idea

**Comment by jaapjansma** [comment]
The solution we came up with is to develop a flexible logging solution. Where the actual implementation of the logger is done in another extension rather than in Civirules
