### ISSUE TITLE
Tag release?

### ISSUE THREAD

**Issue by JoeMurray** [CiviCooP/org.civicoop.civirules#40]
Could you tag the commit that was used for the release tarball?

**Comment by jaapjansma** [comment]
Why?

**Comment by JoeMurray** [comment]
So that it is easier to diff changes between auto distributed version and latest in repo, especially as it is not clear if latest in repo is dev, alpha, beta or stable state.

**Comment by jaapjansma** [comment]
We don't have an auto distributed version and we do not have a dev, alpha, beta or stable state.
