### ISSUE TITLE
Two notices appear when editing a delay in an existing rule

### ISSUE THREAD

**Issue by ErikHommel** [CiviCooP/org.civicoop.civirules#45]
These notices appear if I edit a delay on an existing Rule action:
    Notice: Undefined index: rule_action_select in CRM_Civirules_Form_RuleAction->postProcess() (line 76 of /var/www/civirules/sites/all/modules/civicrm_extensions/org.civicoop.civirules/CRM/Civirules/Form/RuleAction.php).
    Notice: Undefined index: action_id in CRM_Civirules_Form_RuleAction->postProcess() (line 95 of /var/www/civirules/sites/all/modules/civicrm_extensions/org.civicoop.civirules/CRM/Civirules/Form/RuleAction.php).

**Comment by ErikHommel** [comment]
This only shows when the action does not have a delay yet

**Comment by jaapjansma** [comment]
I don't get those notices

**Comment by ErikHommel** [comment]
I will have a look at a later point

**Comment by ErikHommel** [comment]
Unable to reproduce with CiviCRM 4.6.10 with latest version of code. I do get this notice in 4.4:
Notice: Undefined property: CRM_Civirules_BAO_RuleAction::$ignore_condition_with_delay in CRM_Civirules_Form_RuleAction->setDefaultValues() (line 156 of /var/www/mafdev/sites/default/civicrm_extensions/org.civicoop.civirules/CRM/Civirules/Form/RuleAction.php).
