### ISSUE TITLE
Breaks saving feature after updating to 1.1

### ISSUE THREAD

**Issue by Cullpepper** [CiviCooP/org.civicoop.civirules#46]
I used the automatic updating feature to bump civirules up to 1.1. After that, I could not save changes to contact profiles or contributions.

Disabling civirules restored the correct saving behavior. Sorry, this isn't a good bug report, but I'm not sure how to provide more useful information.

**Comment by PalanteJon** [comment]
FWIW, I have a client running CiviRules 1.1 with Civi 4.6.9 on Wordpress (4.3? 4.3.1?) and they don't experience this, so there's probably a confounding factor here.

As for more useful info - is there an error in your Apache error log (or PHP interpreter, if not using Apache+mod_php)?  Maybe in your CiviCRM log, though that's less likely.

**Comment by ErikHommel** [comment]
Tested with 4.6.10, not able to reproduce reported issue
