### ISSUE TITLE
Choose location type in conjunction with the email-api

### ISSUE THREAD

**Issue by magnolia61** [CiviCooP/org.civicoop.civirules#52]
It would for us be really useful to be able to select the location type configuring a civirule in conjunction with the email-api. If that would work we could send a mail to the work-mail of private mail.

We do not currently have funds to support this, but we have time we can offer testing something on various CMS and civicrm versions.

**Comment by ErikHommel** [comment]
@magnolia61 Do you mean that you should be able to select the location type in the action 'Send Email' (with primary as default)? How do you picture this? Should this then always send mail to the home location? Or should there be a sequence?

**Comment by magnolia61** [comment]
I think the best flow would be that it would select primary by default (like it is now),
but that in the action 'Send Email) it can be configured to select another location type (work/home/other). Selecting that should then overrule the primary email address.

In civicrm bulk mailing it is already possible to select (and by that overrule the location type).
It is usefull in scenario's where you want to mail specifically on their work of home email (depending on the condition). Does this clarify a little of confuse all the more? :-)

**Comment by ErikHommel** [comment]
@magnolia61 It does help, but I am trying to generalize it too :-). Would it not make more sense to set to either primary or mailaddress flagged as bulkmail? My concern is that using a location type for a CiviRule might automatically fire unwanted emails to unwanted addresses. I would imagine you would not immediately think of CiviRules if someone calls and says he does not want to receive those kind of mails on his email.

**Comment by magnolia61** [comment]
I agree the emailapi is very powerfull and therefor proper though must be given to all side effects and (un)wanted behaviour. It should respect the 'on hold' status, and (like the civimail functionality) should offer primary by default and other location types optionally.
To clarify a little I can describe how we use location types in our camp management. For our summercamp event registrations we use it in two different ways. 
1) For kids <18 years old one emailadres is that of the kid itself (locationtype home/primary), the other is that of one of the parents (locationtype parent). This will help us to send most emails to the parents before the camp starts and some specially to the kid/youngster that will visit the camp.
2) For our campleaders we register a referal, and collect that referal email adress as location type (referral). This will help us send a mail 2 weeks after registration to the person the campleader sugested as a referral person.
I can understand not everyone will use the location types in this way but it would save us a lot to be able to automate the referral questionaire sending and the mails kids and parents get before the event. 
More general I think civirules/emailapi should be able to overrule the location type (primary) in cases where mailing to home of work is more appropriate (like is possible in civimail).
Optionally maybe it would be an option to have a special footer to notify people got the email through civirules?

**Comment by jaapjansma** [comment]
@magnolia61,

I was reading and discussing this with @ErikHommel and I do think you should rethink your setup. You are sendning e-mails to parents and to referals. Both of them are different persons in real life so wouldn't be better to setup a relationship between child and parent and between camp leader and referal? That way you keep track of your communication history with each person. 

Jaap

**Comment by ErikHommel** [comment]
On top of that, I think if we do change the location type we should not only think of the automation of the workflow, but also what is reasonibly easy to see for the contactperson who has a contact on the phone asking how he/she got this email on that specific emailaddress?

**Comment by ErikHommel** [comment]
Moved the issue to the email API (as it belongs there): 
https://github.com/CiviCooP/org.civicoop.emailapi/issues/19

**Comment by ErikHommel** [comment]
Now fixed in release 1.16 of the Email API @magnolia61
