### ISSUE TITLE
Feature request: Action for setting field value

### ISSUE THREAD

**Issue by samuelvonstachelski** [CiviCooP/org.civicoop.civirules#56]
I can make condition queries to any field values.
Is it possible to provide something similar for actions (setting instead of getting)? Then one could easily build any desired kind of action oneself.

**Comment by jaapjansma** [comment]
Difficulty here is probably that you want to reuse some data from the trigger e.g. the contact_id or the event_id if a trigger is event etc... How are we going to use that data?

**Comment by samuelvonstachelski** [comment]
I see your point. Now I am clear about why this feature was present in the first drafts (https://wiki.civicrm.org/confluence/display/CRM/CiviRules+extension#CiviRulesextension-Setdatavalueformsequence) but omitted in the implementation.
Well, I am going to write my own action then.

**Comment by jaapjansma** [comment]
@samuelvonstachelski  If you have a brilliant idea to implement this you are more than welcome to contribute this to the civirules extension. 
Also note that for development purposes we have a basic api action which you could extend and tweak for your own action. E.g. you have only to provide the parameters, entity, action and the user interface
See for example the add activity action. Which shows the activity type, subject and assigned to in the user interface but upon execution translate this to an api action.

**Comment by samuelvonstachelski** [comment]
Thanks for the hints.
In case I need civirules for a lot of automation tasks, I would really consider to develop such a thing and of course contribute what I have.
