### ISSUE TITLE
Facilitate conditions based on relative dates

### ISSUE THREAD

**Issue by elcapo** [CiviCooP/org.civicoop.civirules#58]
We can easily create conditions based on constant values, like:

> Country of residence of a contact must be **Spain**

where "Spain" would be a constant we write or chose from a list.

When working with dates, I've found difficulties because normally conditions are meant to be created in function of "today", wich is a variable. So I've created a draft (see the link below) that facilitates creating conditions like:

> Activity Date must be at least **one** week old

It adds three new options for every date field, when creating conditions:

![new-options](https://cloud.githubusercontent.com/assets/1746692/12782922/22ec6f18-ca76-11e5-89e7-a761373e9d33.png)

Then, when running the condition, it calculates the diff between the dates in days, months or years and applies the value written with the condition (1 day, 2 months, etc).

The code is here: https://github.com/elcapo/org.civicoop.civirules/commit/61adcd660b0c91e18924e080d558298e5b5be9f7

Can you take a look at it and give me some feedback? Thanks!

**Comment by jaapjansma** [comment]
Personally I would leave the field as it is and would add the relative comparison to the operator list. And only have relative date operators when the field is of a date type.

**Comment by elcapo** [comment]
Actually, the way you propose would be a little simpler for the user because it wouldn't have to multiply the amount of times every date field is shown. In the approach above, every date field appears 4 times!

I'll try to send a new version tomorrow.

**Comment by elcapo** [comment]
I'm trying a second approach where there are no User Interface changes. The only change is you can write an integer number when setting a condition for a date field:

**An integer number with a "plus" prefix will be interpreted as days from today.**

> +15

**An integer number with a "minus" prefix will be interpreted as days to today.**

> -3

By writting +/- a number, you can easily set a reference date, that will be calculated when the system is evaluating the condition. What seems interesting is that with this approach you're free to chose the operator you want ( >=, >, <, <=, etc ), so it will be applied to the referenced date ( as in TODAY + 5 ).

To achieve this, I only wrote a few lines at the beggining of getComparisonValue(): https://github.com/elcapo/org.civicoop.civirules/commit/1094d07604560ab69f72842b90254699830bdd2c

**Comment by elcapo** [comment]
There are still things I don't like, like looking for the word "date" in the name of the field, instead of actually looking for its type. (Wrote the code just to make the discussion easier.)

**Comment by jaapjansma** [comment]
Great @elcapo! Looks good. You can use the getfield api of an entity or the DAO getFields method to determine the type of the field. I use this kind of code to determine whether the field is a select field

**Comment by elcapo** [comment]
I've achieved it with this approach: https://github.com/elcapo/org.civicoop.civirules/commit/04d390bfb87c231ed9ed3328870f656624a4e3e3. Is there a way I can do it with a one-line-call?

**Comment by jaapjansma** [comment]
@elcapo I am not sure whether it is possible with a one-line call... Your code looks good

**Comment by elcapo** [comment]
Hello again Jaasp!

Sorry for the silence! I've been working in other parts of this project, so I left this issue for the ending.

I've been trying the code I sent the 5th February and it works nice to me. To explain what it does, I've prepared a set of four screenshots:

**Fech activities by type and status**

(This part is not directly related with this issue, but it helps me to explain the case.) I'm using an own cron trigger class to fetch activities by type and status. This class allows the user to specify the type and status of the activities to fetch (in the screenshot, we're fetching "Scheduled / Meetings".

![1 fetch-activities](https://cloud.githubusercontent.com/assets/1746692/13602473/cd830d42-e52e-11e5-821b-c25006616d84.png)

**Field value comparison**

Now, I want to condition the execution of the action to those scheduled meetings with a date this week. To do so, I'll use a field value comparison.

![2 field-value-comparison](https://cloud.githubusercontent.com/assets/1746692/13602498/e876fcb2-e52e-11e5-88ea-84d65ff11a37.png)

**Relative date conditions**

Here comes the new stuff. If the field is a date, time or datetime field, you can write a date (as you could do before), or you can write something that the [strtotime function](http://php.net/manual/en/function.strtotime.php) would understand.

![3 date-condition](https://cloud.githubusercontent.com/assets/1746692/13602551/23af58a6-e52f-11e5-9656-a405ddd5db44.png)

**That's it!**

The screenshots were taken today (8th March, Tuesday), so "last Monday" refers to yesterday. If we open the rule, we'll actually see the corresponding value of the date.

![4 fetch-activities-by-relative-date](https://cloud.githubusercontent.com/assets/1746692/13602647/bdac2484-e52f-11e5-8e6b-6ed81e4fe007.png)

Do you think this is general, as for being in the mainstream extension? (If it's ok to you, I can prepare a pull request.)

**Comment by jaapjansma** [comment]
Hey @elcapo 

Wow I am impressed! That looks great! 

Jaap

**Comment by jaapjansma** [comment]
@elcapo I have merged your PR.

**Comment by alani1** [comment]
@elcapo Thanks for this patch and PR! I have noticed it does not work with timestamp fields. I am trying to use the created_date of Contact. When I add someting like in the function isDateField 
`$timestampType`` = CRM_Utils_Type::T_TIMESTAMP;
would that be enough? Or is more than this needed?

**Comment by magnolia61** [comment]
@elcapo Your work on this is so great and opens so much flexibility I think it would be super awesome if you could also submit this to the Advanced Search Builder in CiviCRM core. Any chance you could create a PR for that?
