### ISSUE TITLE
event context available?

### ISSUE THREAD

**Issue by magnolia61** [CiviCooP/org.civicoop.civirules#59]
It seems the event context is not available for event tokens in the emails send as an action through the email api. Is that correct and expected or am i doing something wrong?

For instance: when an event participant status is changed from 'pending' to 'registered' I would like to send a confirmation mail with some event info (title, date, etc).

**Comment by jaapjansma** [comment]
That is right the event context is not available in the send e-mail action.

**Comment by encircle** [comment]
@jaapjansma is the same true for other contexts, or is this just for CiviEvents? E.g. is the context for CiviCase event triggers passed to the email API to allow custom fields in Cases to be embedded in emails? Thanks for clarifying.

**Comment by jaapjansma** [comment]
The same is true for all other contexts. And I don't think there is an easy way to make certain contexts available to the e-mail api. At least I cannot think of an easy solution.
