### ISSUE TITLE
Email Action Example

### ISSUE THREAD

**Issue by encircle** [CiviCooP/org.civicoop.civirules#60]
Reading the docs here: https://wiki.civicrm.org/confluence/display/CRMDOC/CiviRules+Basic+Example+Immediate+Processing 
It says:
> In this example I will select the action Send e-mail and leave the No Delay. If I click Save I get a form where I can enter details about the email.

However the "Send Email" Action is not available to select. The following Actions are packaged in the latest version of the extension:-

`<option value="0"> - select - </option>
	<option value="2">Add activity to contact</option>
	<option value="6">Add contact to group</option>
	<option value="8">Add tag to contact</option>
	<option value="7">Remove contact from group</option>
	<option value="9">Remove tag from contact</option>
	<option value="1">Set Contact as Donor</option>
	<option value="5">Set Thank You Date for Contribution</option>
	<option value="4">Set subtype for contact</option>
	<option value="3">Soft delete a contact</option>
`
This makes it hard for newcomers to follow the basic example in the documentation they are taken to after install and will deter many from progressing.

Could you please add the basic email example to the out of the box actions? This way the user experience will not be broken and will encourage uptake of the extension.

Many thanks, and great efforts getting this extension live! Much appreciated!

**Comment by ErikHommel** [comment]
Thanks for the pointer, will do. To be able to send email you also need the email extension: https://civicrm.org/extensions/e-mail-api
(and the same for sms and pdf)

**Comment by encircle** [comment]
@ErikHommel my bad, was working on a fresh install and the email api wasn't there! thanks!

**Comment by ErikHommel** [comment]
@encircle stills should have warned you in the wiki :-) I have updated the documentation.
