### ISSUE TITLE
Daily trigger group should allow a condition "day of the month"

### ISSUE THREAD

**Issue by PalanteJon** [CiviCooP/org.civicoop.civirules#66]
I was looking at CiviRules as a way to send a message to people who are in a particular smart group once a month.  It seems like the "daily trigger" would work if there were a condition to set the day of the month.  If I wrote a PR to add that condition, would that be something you all are interested in?

I realize that it would be lovely to have a full set of day/date options, similar to the recurring event engine, but that seems like a much bigger bite to chew off.

**Comment by jaapjansma** [comment]
Hey @JohnFF 

I am wondering whether it is something similair to what @elcapo has done in issue #58 

Thanks,
Jaap

**Comment by PalanteJon** [comment]
Hi Jaap,

This is different.  My use case is, "Once a month, send an email to everyone who has two or more failed recurring contributions."  If it were just one failed recurring contribution, I could make a rule right now (and in fact have).  However, to find people with multiple failed contributions requires a custom search, and thus a smart group.  I want the ability to send a message every month, automatically, to members of a smart group, and #58 doesn't facilitate that.

You all seem to be relatively willing to accept PRs, so I'll put this on my to-do list.

Jon (not JohnFF)

**Comment by ErikHommel** [comment]
Hi @PalanteJon, are you not worried that you will incur some of the performance problems linked to Smart Groups? So what is the business use case? Would you not want to act immediately when a recurring failed, or alternatively create a specific DailyTrigger rather than one working on Smart Groups?

**Comment by PalanteJon** [comment]
@ErikHommel If you can think of a way to accomplish what I'm trying to do without smart groups I'd certainly welcome it!  To be clear - we DO want a particular message to go out when a failed contribution is added, and that we can do within CiviRules now.

However, we want a different message to go out if this isn't your first failed contribution.  I don't see a way to do this without smart groups and a custom search.

Finally - I tried abstracting the problem.  "I want a message to go out to members of a particular group (smart or not) on the 15th of each month" sounds like a CiviRule others might want.  Otherwise I'd just write an extension and call it a day :)

**Comment by JohnFF** [comment]
I normally wouldn't weigh in, but I was notified of this...

Two things to make:
CiviRulesTrigger: on Xth day of the month (also look at "first Tuesday" "third Wednesday" etc. PHP's DateTime constructor is *really* flexible.

CiviRuleAction: empty everyone from group X.

If you hurry, you might get them in for v1.3 with all my fixes and features in!

**Comment by elcapo** [comment]
I Jon! Not sure if I understood what you want to do but in [this comment](https://github.com/CiviCooP/org.civicoop.civirules/issues/58#issuecomment-193780880), I tried to explain how you can use the DateTime constructor with the PR of #58. Breafly, the idea is:

> If the field in your Field value comparison is a date time field, then you are allowed to use any expression that the PHP DateTime constructor would accept, such as "last Monday", etc.

**Comment by PalanteJon** [comment]
@elcapo Thank you, I'll check this out.  I'm aware of the DateTime constructor, and have considered using it in my "relative date constructor" work: https://issues.civicrm.org/jira/browse/CRM-16195.

I think your code from #58 might work, except I don't think there's currently a way to compare against today's date instead of a field.  I'll look into piggybacking on your work though.
