### ISSUE TITLE
CiviCRM 4.7.6 Undefined variable on comparison tests

### ISSUE THREAD

**Issue by gah242s** [CiviCooP/org.civicoop.civirules#68]
Utilizing CiviCRM 4.7.6 on Wordpress 4.5.1, I'm getting an undefined variable PHP Notice when adding conditions that compare.  A simple condition for checking for an age bracket, or seeing if case status changes will throw the error with debugging turned on.  Unfortunately, the comparison tests won't run, making the rules rather, well, useless.  Remove the condition and run the same procedures, such as changing a case status, and the rules trigger as expected.

The two errors thrown are:
Notice: Undefined variable: key in civicrm/ext/org.civicoop.civirules/CRM/CivirulesConditions/Generic/FieldValueChangeComparison.php on line 42
 Notice: Undefined variable: key in civicrm/ext/org.civicoop.civirules/CRM/CivirulesConditions/Generic/FieldValueChangeComparison.php on line 75

Both lines are the same (Lines 42-47):

```
    if (!empty($this->conditionParams[$key])) {
      return $this->conditionParams[$key];
    } else {
      return '';
    }
```

**Comment by jaapjansma** [comment]
This is fixed in https://github.com/CiviCooP/org.civicoop.civirules/pull/135 I will close this issue.
