### ISSUE TITLE
Unfriendly notice when using CiviRules Do DownGrade Example 

### ISSUE THREAD

**Issue by mercimukwe** [CiviCooP/org.civicoop.civirules#69]
I installed the CIviRules module extension for use for a project while trying the this example [CiviRule Example Donor Classification](https://wiki.civicrm.org/confluence/display/CRMDOC/CiviRules+Example+Donor+Classification) on adding an action for a corresponding trigger, I get this unfriendly notice that seemed me like an error, May be it could wel not be shown as many users may think that they might have spoiled something.

Even though the action is still validated!! below is a screen shot

![noticecivirules](https://cloud.githubusercontent.com/assets/18053120/14920894/550f1014-0e27-11e6-9716-26896b3ac104.png)

**Comment by gah242s** [comment]
Looks related to https://github.com/CiviCooP/org.civicoop.civirules/issues/68

**Comment by ErikHommel** [comment]
Fixed with #135
