### ISSUE TITLE
Can not save Event page changes.. on 4.6.16

### ISSUE THREAD

**Issue by tapashdatta** [CiviCooP/org.civicoop.civirules#71]
here is the log:

```
May 16 15:21:16  [info] 
$Fatal Error Details = array(3) {
  ["message"]=>
  string(25) "id is not a valid integer"
  ["code"]=>
  NULL
  ["exception"]=>
  object(CiviCRM_API3_Exception)#280 (8) {
    ["extraParams":"CiviCRM_API3_Exception":private]=>
    array(7) {
      ["error_field"]=>
      string(2) "id"
      ["type"]=>
      string(7) "integer"
      ["error_code"]=>
      int(2001)
      ["entity"]=>
      string(11) "CustomField"
      ["action"]=>
      string(3) "get"
      ["is_error"]=>
      int(1)
      ["error_message"]=>
      string(25) "id is not a valid integer"
    }
    ["message":protected]=>
    string(25) "id is not a valid integer"
    ["string":"Exception":private]=>
    string(0) ""
    ["code":protected]=>
    int(0)
    ["file":protected]=>
    string(47) "/www/demo/sites/all/modules/civicrm/api/api.php"
    ["line":protected]=>
    int(45)
    ["trace":"Exception":private]=>
    array(23) {
      [0]=>
      array(4) {
        ["file"]=>
        string(139) "/srv/www/rldb/sites/all/modules/civicrm_custom_scripts/civicrm_extensions/org.civicoop.civirules-master/CRM/Civirules/Utils/CustomField.php"
        ["line"]=>
        int(25)
        ["function"]=>
        string(12) "civicrm_api3"
        ["args"]=>
        array(3) {
          [0]=>
          string(11) "CustomField"
          [1]=>
          string(9) "getsingle"
          [2]=>
          array(1) {
            ["id"]=>
            string(3) "pre"
          }
        }
      }
      [1]=>
      array(6) {
        ["file"]=>
        string(145) "/srv/www/rldb/sites/all/modules/civicrm_custom_scripts/civicrm_extensions/org.civicoop.civirules-master/CRM/Civirules/Utils/CustomDataFromPre.php"
        ["line"]=>
        int(40)
        ["function"]=>
        string(24) "isCustomFieldMultiselect"
        ["class"]=>
        string(31) "CRM_Civirules_Utils_CustomField"
        ["type"]=>
        string(2) "::"
        ["args"]=>
        array(1) {
          [0]=>
          string(3) "pre"
        }
      }
      [2]=>
      array(6) {
        ["file"]=>
        string(145) "/srv/www/rldb/sites/all/modules/civicrm_custom_scripts/civicrm_extensions/org.civicoop.civirules-master/CRM/Civirules/Utils/CustomDataFromPre.php"
        ["line"]=>
        int(22)
        ["function"]=>
        string(13) "setCustomData"
        ["class"]=>
        string(37) "CRM_Civirules_Utils_CustomDataFromPre"
        ["type"]=>
        string(2) "::"
        ["args"]=>
        array(4) {
          [0]=>
          string(5) "Event"
          [1]=>
          string(3) "pre"
          [2]=>
          string(2) "19"
          [3]=>
          string(2) "id"
        }
      }
      [3]=>
      array(6) {
        ["file"]=>
        string(117) "/srv/www/rldb/sites/all/modules/civicrm_custom_scripts/civicrm_extensions/org.civicoop.civirules-master/civirules.php"
        ["line"]=>
        int(133)
        ["function"]=>
        string(3) "pre"
        ["class"]=>
        string(37) "CRM_Civirules_Utils_CustomDataFromPre"
        ["type"]=>
        string(2) "::"
        ["args"]=>
        array(4) {
          [0]=>
          string(4) "edit"
          [1]=>
          string(5) "Event"
          [2]=>
          string(2) "36"
          [3]=>
          array(41) {
            ["qfKey"]=>
            string(37) "0e554cc8c422b754debfb5d89242f6aa_6085"
            ["entryURL"]=>
            string(160) "https://demo.rldb.info/civicrm/event/manage/registration?reset=1&amp;action=update&amp;id=36&amp;component=event&amp;qfKey=0e554cc8c422b754debfb5d89242f6aa_6085"
            ["is_online_registration"]=>
            string(1) "1" 

it goes on and on for more than 10000 lines..
```

**Comment by parkesdesign** [comment]
@tapashdatta

I'm having exactly the same problem when creating a event with CiviCRM 4.6.18

Sorry but we are not able to provide this at the moment.
One of parameters (value: ) is not of the type Integer

I am not a coder but I would love to learn how to debug and fix this problem. Did you come up with a solution or patch to fix this problem?

**Comment by tapashdatta** [comment]
@parkesdesign Yes, I have managed to sort it out by using a older version of civirules. Latest one with latest CiviCRM 4.6.x was creating lot of troubles, luckily I had a backup and it is stable now.

**Comment by jaapjansma** [comment]
Could you try and test whether the error still exists when you use the latest code from github? because it looks like this has been solved a while ago see also issue #55

**Comment by parkesdesign** [comment]
@jaapjansma I initially tested it using the latest master from GitHub and that is the error I received.

It occurs on any Event Trigger (create,change,delete)

backtrace error is below:

`#0 /var/www/clients/client1/web8/web/sites/all/modules/civicrm/CRM/Core/Error.php(360): CRM_Core_Error::backtrace()
#1 /var/www/clients/client1/web8/web/sites/all/modules/civicrm/CRM/Utils/Type.php(415): CRM_Core_Error::fatal("One of parameters  (value: ) is not of the type Integer")
#2 /var/www/clients/client1/web8/web/sites/all/modules/civicrm/CRM/Core/DAO.php(1251): CRM_Utils_Type::validate(NULL, "Integer")
#3 /var/www/clients/client1/web8/web/sites/all/modules/civicrm/CRM/Core/DAO.php(1168): CRM_Core_DAO::composeQuery("INSERT INTO `civirule_rule_log` (`rule_id`, `contact_id`, `log_date`) VALUES ...", (Array:2), TRUE)
#4 /var/www/clients/client1/web8/web/sites/default/files/civicrm/ext/org.civicoop.civirules/org.civicoop.civirules-master/CRM/Civirules/Engine.php(285): CRM_Core_DAO::executeQuery("INSERT INTO `civirule_rule_log` (`rule_id`, `contact_id`, `log_date`) VALUES ...", (Array:2))
#5 /var/www/clients/client1/web8/web/sites/default/files/civicrm/ext/org.civicoop.civirules/org.civicoop.civirules-master/CRM/Civirules/Engine.php(30): CRM_Civirules_Engine::logRule(Object(CRM_Civirules_TriggerData_Post))
#6 /var/www/clients/client1/web8/web/sites/default/files/civicrm/ext/org.civicoop.civirules/org.civicoop.civirules-master/CRM/Civirules/Trigger/Post.php(81): CRM_Civirules_Engine::triggerRule(Object(CRM_Civirules_Trigger_Post), Object(CRM_Civirules_TriggerData_Post))
#7 /var/www/clients/client1/web8/web/sites/default/files/civicrm/ext/org.civicoop.civirules/org.civicoop.civirules-master/CRM/Civirules/Trigger/Post.php(66): CRM_Civirules_Trigger_Post->triggerTrigger("create", "Event", 12, Object(CRM_Event_DAO_Event))
#8 /var/www/clients/client1/web8/web/sites/default/files/civicrm/ext/org.civicoop.civirules/org.civicoop.civirules-master/civirules.php(137): CRM_Civirules_Trigger_Post::post("create", "Event", 12, Object(CRM_Event_DAO_Event))
#9 /var/www/clients/client1/web8/web/sites/all/modules/civicrm/CRM/Utils/Hook.php(213): civirules_civicrm_post("create", "Event", 12, Object(CRM_Event_DAO_Event))
#10 /var/www/clients/client1/web8/web/sites/all/modules/civicrm/CRM/Utils/Hook/DrupalBase.php(87): CRM_Utils_Hook->runHooks((Array:33), "civicrm_post", 4, "create", "Event", 12, Object(CRM_Event_DAO_Event), NULL, NULL)
#11 /var/www/clients/client1/web8/web/sites/all/modules/civicrm/CRM/Utils/Hook.php(304): CRM_Utils_Hook_DrupalBase->invoke(4, "create", "Event", 12, Object(CRM_Event_DAO_Event), NULL, NULL, "civicrm_post")
#12 /var/www/clients/client1/web8/web/sites/all/modules/civicrm/CRM/Event/BAO/Event.php(110): CRM_Utils_Hook::post("create", "Event", 12, Object(CRM_Event_DAO_Event))
#13 /var/www/clients/client1/web8/web/sites/all/modules/civicrm/CRM/Event/BAO/Event.php(141): CRM_Event_BAO_Event::add((Array:28))
#14 /var/www/clients/client1/web8/web/sites/all/modules/civicrm/CRM/Event/Form/ManageEvent/EventInfo.php(307): CRM_Event_BAO_Event::create((Array:28))
#15 /var/www/clients/client1/web8/web/sites/all/modules/civicrm/CRM/Core/Form.php(345): CRM_Event_Form_ManageEvent_EventInfo->postProcess()
#16 /var/www/clients/client1/web8/web/sites/all/modules/civicrm/CRM/Core/QuickForm/Action/Upload.php(166): CRM_Core_Form->mainProcess()
#17 /var/www/clients/client1/web8/web/sites/all/modules/civicrm/CRM/Core/QuickForm/Action/Upload.php(133): CRM_Core_QuickForm_Action_Upload->realPerform(Object(CRM_Event_Form_ManageEvent_EventInfo), "upload")
#18 /var/www/clients/client1/web8/web/sites/all/modules/civicrm/packages/HTML/QuickForm/Controller.php(203): CRM_Core_QuickForm_Action_Upload->perform(Object(CRM_Event_Form_ManageEvent_EventInfo), "upload")
#19 /var/www/clients/client1/web8/web/sites/all/modules/civicrm/packages/HTML/QuickForm/Page.php(103): HTML_QuickForm_Controller->handle(Object(CRM_Event_Form_ManageEvent_EventInfo), "upload")
#20 /var/www/clients/client1/web8/web/sites/all/modules/civicrm/CRM/Core/Controller.php(353): HTML_QuickForm_Page->handle("upload")
#21 /var/www/clients/client1/web8/web/sites/all/modules/civicrm/CRM/Utils/Wrapper.php(115): CRM_Core_Controller->run()
#22 /var/www/clients/client1/web8/web/sites/all/modules/civicrm/CRM/Core/Invoke.php(286): CRM_Utils_Wrapper->run("CRM_Event_Form_ManageEvent_EventInfo", "New Event", NULL)
#23 /var/www/clients/client1/web8/web/sites/all/modules/civicrm/CRM/Core/Invoke.php(86): CRM_Core_Invoke::runItem((Array:15))
#24 /var/www/clients/client1/web8/web/sites/all/modules/civicrm/CRM/Core/Invoke.php(54): CRM_Core_Invoke::_invoke((Array:3))
#25 /var/www/clients/client1/web8/web/sites/all/modules/civicrm/drupal/civicrm.module(489): CRM_Core_Invoke::invoke((Array:3))
#26 [internal function](): civicrm_invoke("event", "add")
#27 /var/www/clients/client1/web8/web/includes/menu.inc(527): call_user_func_array("civicrm_invoke", (Array:2))
#28 /var/www/clients/client1/web8/web/index.php(21): menu_execute_active_handler()
#29 {main}`

**Comment by parkesdesign** [comment]
@tapashdatta can you please let me know which version of CiviRules you used so I can download it to compare code. The event trigger doesn't work on the lastest 4.7.x version as well so I'm curious as to whats changed. Thanks in advance!

**Comment by parkesdesign** [comment]
@jaapjansma I have just read through issue #55 

The scenario is slightly different from that one. The below has been done on clean installs of CiviCRM 4.6.18 and 4.7.8

1. Download and install the latest master version of CiviRules via github.
2. Create a rule with trigger new event.
3. Create a new event, click save and error message occurs.
4. Go to CiviRules and disable rule.
5. Create a new event, click save and event is created.

The scenario is the same when the trigger is edit and delete event.

Further information - Drupal 7.44, CiviCRM 4.6.18, PHP 5.6.22, mysql 5.5.49

**Comment by jaapjansma** [comment]
@parkesdesign that is a different backtrace then you have posted before. I am not really sure what caused this I need to test it myself and that would probably take some time.

**Comment by jaapjansma** [comment]
@parkesdesign and it could also be that the triggers are not really working with Events. I have never tested a use case with an event trigger.

**Comment by parkesdesign** [comment]
@jaapjansma Okay I see, I read the original post title as Can not save Event page changes and thought @tapashdatta issue was similar to mine since the error code was the same. 

Sorry but we are not able to provide this at the moment.
One of parameters (value: ) is not of the type Integer

I appreciate the time and effort civicoop has put into developing and sharing this extension, are you able to point me into any direction as to how I can try to debug this? searching documentation online points to how to create custom conditions not triggers or is this more of a wishlist fix?

**Comment by parkesdesign** [comment]
@jaapjansma Also since this bug is different should I create a new issue log stating the problem?

**Comment by jaapjansma** [comment]
Yes that would be better I guess. I will comment in the new issue.

**Comment by jaapjansma** [comment]
I assume that this issue is resolved over time and will close it for now.
