### ISSUE TITLE
Relationship trigger

### ISSUE THREAD

**Issue by jaapjansma** [CiviCooP/org.civicoop.civirules#83]
Create a trigger for relationship which fires on both contact a and contact b of the relationship. 
Also remove the contact_a part of the TriggerData class. 

See https://github.com/CiviCooP/org.civicoop.civirules/pull/82/commits/2d9bdd002b249e384a47a7ed994be855cbcf89ad

And see https://github.com/CiviCooP/org.civicoop.civirules/pull/82 for more information

**Comment by systopia** [comment]
Thanks @jaapjansma. How would you solve this? You could add "Contact A" and "Contact B" entities to the trigger data, is that what you had in mind?

**Comment by jaapjansma** [comment]
I would solve this by creating a seperate Trigger class for relationship, just as we did for GroupContact and for cases. That class would then fire the trigger for both contact a and contact b.

**Comment by systopia** [comment]
Ah, I understand. But doesn't that mean, that if you're only interested in the relationship entity it'll be triggered twice?

**Comment by jaapjansma** [comment]
@systopia I have posted a solution into a PR https://github.com/CiviCooP/org.civicoop.civirules/pull/84

**Comment by jaapjansma** [comment]
@systopia and it means indeed that if you are interested in the relationship entity it gets triggered twice.

**Comment by systopia** [comment]
@jaapjansma ok, then what kind of condition could we have so the actions will only be executed once?

**Comment by jaapjansma** [comment]
@systopia there is a condition called relationship is contact a and a condition which is called relationship is contact b

**Comment by systopia** [comment]
I'm not sure I understand the concept. Let's say I want to send an email to an unrelated contact every time a relationship is created. How do these conditions help me?

**Comment by jaapjansma** [comment]
Lets say you have a relationship called 'Is Child Of' Lets say that contact a is the parent and contact b is the child.

When you want to send an e-mail to the parent each time this relationship is created you add a rule:
- Trigger = Relationship is added
- Condition = **Relationship is contact a**
- Action = Send E-mail

See you want to send an e-mail to the child each time this relationship is created you add a rule:
- Trigger = Relationship is added
- Condition = **Relationship is contact B**
- Action = Send E-mail

**Comment by jaapjansma** [comment]
If you want to send an e-mail to both the parent and the child you remove the condition and it will send two e-mails one to the parent and one to the child

**Comment by systopia** [comment]
No, I meant: "I want to send an email to an *unrelated* contact", i.e. a contact that has no part in the relationship. As far as I understand, your approach focuses exclusively on the idea, that you want to do something to either (or both) of the contacts. But what if you don't? 

I'm not sure triggering rules twice for one event (create relation) isn't going to cause problems down the road... What do you think?

**Comment by jaapjansma** [comment]
Ah I see... Good question.... I would setup a rule with trigger Relationship is Added. Then a condition with either (Relationship is contact A or Relationship is Contact B) and then an action send e-mail to someone else

The condition is there to prevent that the action will run twice.

**Comment by davejenx** [comment]
@jaapjansma Looks as though there is no condition for relationship type at the moment, is that correct?

**Comment by jaapjansma** [comment]
@davejenx you could probably you use the condition: field value comparison.

**Comment by davejenx** [comment]
@jaapjansma Perfect, thank you.

**Comment by davejenx** [comment]
@jaapjansma Sorry if this is too far off topic. Suppose one wanted a rule to send an email to a related contact (with specified relationship type) when a membership is updated. One way I can see would be to implement a custom action to email a related contact. Is there another approach where one could introduce the related contact into the rule, so that they become "the contact", then use the standard send email action?

**Comment by jaapjansma** [comment]
@davejenx indeed it is a bit off topic. But it is a really good question. You could create a custom action for that which is called send e-mail to related contact. But if you want a more general approach that would be difficult because it means that we need to change the contact upon which the trigger is firing.

**Comment by kngs** [comment]
This very close (but almost opposite to what I want - maybe a more general application).  I have a parent/child relationship.  When the parent gets an email regarding the child, I want to record an activity (easily accessible) in the child's record that says an email was sent to the parent, regarding the child, but don't want the child to get the email.   Basically, I want a CiviRule (or something) that let's me trigger an action on a third party (possibly accessible through a custom contact reference field associated with the initial action).  Did anything happen with this and is my situation an extension of it?

**Comment by ErikHommel** [comment]
@kngs nothing happened with this. What you are suggesting requires a new condition and action. Nothing happened because at the moment we do not have a customer who wants to fund that development. Perhaps you would either consider to develop this or fund this?

**Comment by jaapjansma** [comment]
I will close this issue as the relationship trigger is already present in civirules.
