### ISSUE TITLE
Disabling/re-enabling CiviRules results in loss of rule actions

### ISSUE THREAD

**Issue by PalanteJon** [CiviCooP/org.civicoop.civirules#86]
Not 100% sure whether to file this here or against the emailapi extension.  I'm willing to submit a PR if someone can give me a hint on where to look (and if there's an unexpected consequence of changing this behavior).

In my environment, I have CiviRules 1.2 installed with the Email API extension.  This extension adds the "emailapi_send" action to the `civirule_action` table.

I instructed a client to temporarily disable CiviRules to work around the issue fixed in issue #85 before I'd found the patch.  **Disabling CiviRules caused the emailapi_send action to be deleted from the `civirule_action` table.**  Due to foreign key constraints, this caused all actions that relied upon this rule to disappear.  Upon re-enabling CiviRules, the action was re-added to the table - but of course, the rules from `civirule_rule_action` were still deleted.

My expected behavior is that disabling CiviRules does NOT remove the `emailapi_send` action from the table.

**Comment by jaapjansma** [comment]
I do think reporting it here seems the good approach. The Email API extension (and other extensions) uses the civicrm managed entities approach to add civirules actions with an additional check whether civirules is installed and enabled. The managed entities uses the civirules api for adding actions and conditions. So a disabled civirules does also remove the api calls (I would assume).

So how should we handle this use case?

**Comment by PalanteJon** [comment]
Ah, I see - thank you Jaap.

What if instead of using the managed entity approach, we moved the creation of the CiviRuleAction into `emailapi_civicrm_install`?  You could remove the record via the `emailapi_civicrm_disable` hook.

**Comment by jaapjansma** [comment]
Well what would happen if you installed Email api first and then install CiviRules? Would you expect the action to appear? In your case the action would not be created and both extension should be usable without the other.

**Comment by PalanteJon** [comment]
Hi @jaapjansma - sorry I never got back to you on this!  I happened to think of it today because I'm developing almost identical functionality in my own extension.  I'm going to close this since there's an open PR in the emailapi project that solves this.
