### ISSUE TITLE
Not all custom fields are available in Condition Parameters

### ISSUE THREAD

**Issue by pmosey** [CiviCooP/org.civicoop.civirules#93]
As referenced [here](http://civicrm.stackexchange.com/questions/13198/when-creating-or-editing-a-civirule-not-all-custom-fields-are-available-in-cond), the field select list on the CiviRules Edit Condition parameters form appears to be incomplete.

I see most custom fields tied to activities that were created but the list is not complete. It appears to get cut off.

The fields are listed in the order they were created. In our case, the list cuts off between custom field sets with the ids 92 and 93 and displays 154 fields.

**Comment by ErikHommel** [comment]
Hi Paul, thanks for reporting this! Would you be able to fix it too? Let me know if you need any pointers?

**Comment by pmosey** [comment]
Pointers appreciated!

**Comment by ErikHommel** [comment]
@pmosey  First of all: which condition are you working with?
Assuming you are working with the **field value comparison** condition, there is a class `CRM_CivirulesConditions_Form_FieldValueComparison` with a function to get the custom fields for an entity. That would be my starting point for debugging. Does that give you a start?

**Comment by pmosey** [comment]
Thanks, I'll head down that path.

**Comment by jaapjansma** [comment]
@pmosey I dont see what the real problem is. My assumption is that you have lots of customs fields and custom groups (probably one of them more than 25).

**Comment by jaapjansma** [comment]
I discovered that the fetching of custom groups and custom fields (within a custom group) was limited by max 25 and hopefuly my fix did solve your issue @pmosey. 
I will close this issue for now and if it is still an issue feel free top reopen it.
