### ISSUE TITLE
'Membership is changed' appears to not work as Linked Trigger, but error is error message appearing incorrectly

### ISSUE THREAD

**Issue by joemcl** [CiviCooP/org.civicoop.civirules#94]
We're on CiviCRM 4.6.19 and Drupal 7.50.
I've just added and installed CiviRules 1.2 from master.
I'm trying to create my first rule. I selected "Membership is changed" as the Linked Trigger. Other settings are in the screenshot.
Yet, when saving the new rule, I see the error message "Please correct the following errors in the form fields below: Select Trigger is a required field" and I can't save the new rule.
I'm going to start from scratch to see if there is another trigger setting I missed.
Any clues to fixing the error or removing the error message are appreciated. Thanks!

![civirules - selecttrigger](https://cloud.githubusercontent.com/assets/3912434/17447622/86350606-5b1d-11e6-96ce-e9469ac08037.png)

**Comment by joemcl** [comment]
Also see the Stack Exchange Q and A [here](http://civicrm.stackexchange.com/questions/14236/i-have-selected-a-linked-trigger-for-a-new-rule-created-using-civirules-so-why?noredirect=1#comment15794_14236)

**Comment by ErikHommel** [comment]
Sorry for a late reply, holidays :-) The error would be a result from form validation, probably in `CRM_Civirules_Form_Rule` in the validateTriggerEmpty function. It is strange because this error does not occur on any other rule as far as I know. It would be great if you can fix this, let me know if you need more help?

**Comment by joemcl** [comment]
Erik, thanks for the reply. I've asked Peter Davis for some help from the Fuzion crew, he is looking at that. I will take a look myself but I probably don't have the chops to fix it.

**Comment by joemcl** [comment]
Erik FYI, I'm getting the same error message ( ""Please correct the following errors in the form fields below: Select Trigger is a required field" ) when the Linked Trigger is Activity is added. 
![civirulestriggeractivityisadded](https://cloud.githubusercontent.com/assets/3912434/17684505/59b38b2e-632a-11e6-88b8-13659825fa6d.png)

**Comment by joemcl** [comment]
UPDATE: So I ignored the error message, saved the new rules, enabled them and tested them. For the first, I expired my own membership. and the desired Actions were taken - an Activity to send a postcard was assigned to me, another Activity to make a phone call was assigned to me, and I received an e-mail. For the second, I added a new Activity as the trigger, and the desired Actions occurred.  So: the error at this point could just be that the error message ""Please correct the following errors in the form fields below: Select Trigger is a required field" should not appear.

**Comment by ErikHommel** [comment]
Okay, so functionally everything works but is sends unwarranted error message, correct?

**Comment by joemcl** [comment]
Erik, seems so, functioning is correct, at least for the two rules I've created so far, but the error message appears when creating the rule, which makes a user think that the rule won't function correctly.

**Comment by ErikHommel** [comment]
@joemcl I can imagine :-) I will be working with CiviRules at Amnesty next week, I will try to squeeze this one in too.

**Comment by joemcl** [comment]
Erik, terrific, that's great. And from what I've seen so far, CiviRules looks really useful. Big thanks to you, Jaap, MAF Norge, Amnesty and other folks for making it happen.

**Comment by joemcl** [comment]
Leaving this issue open for now

**Comment by petednz** [comment]
Happens for Contribution is Added too. but that was 1.2. Same false error.

**Comment by ErikHommel** [comment]
Fixed with fix for #97

**Comment by joemcl** [comment]
@ErikHommel terrific thanks so much and let's catch up re the discussion on my org helping to pay for this.

**Comment by ErikHommel** [comment]
@joemcl I think it is best if you save it for your next CiviRule wish. MAF Norge picked this one up, we will find you for a next one :-)

**Comment by joemcl** [comment]
@ErikHommel and @jaapjansma - thanks again and thanks to MAF Norge for this and its prior generous contributions to make CiviRules happen!
