### ISSUE TITLE
Issue on civicrm 4.7.7

### ISSUE THREAD

**Issue by sgladstone** [CiviCooP/org.civicoop.civirules#96]
When trying a simple rule( whenever a certain tag is added to a contact, add the contact to a group) in my 4.7 environment, I get the following error:

$backTrace = #0 /home/sepg1/public_html/sites/all/modules/civicrm/CRM/Core/Error.php(329): CRM_Core_Error::backtrace("backTrace", TRUE) #1 /home/sepg1/public_html/sites/all/modules/civicrm/CRM/Utils/Type.php(424): CRM_Core_Error::fatal("One of parameters (value: ) is not of the type Integer") #2 /home/sepg1/public_html/sites/all/modules/civicrm/CRM/Core/DAO.php(1347): CRM_Utils_Type::validate(NULL, "Integer") #3 /home/sepg1/public_html/sites/all/modules/civicrm/CRM/Core/DAO.php(1264): CRM_Core_DAO::composeQuery("INSERT INTO `civirule_rule_log` (`rule_id`, `contact_id`, `log_date`) VALUES ...", (Array:2), TRUE) #4 /home/sepg1/public_html/civicrm_extensions/org.civicoop.civirules/CRM/Civirules/Engine.php(285): CRM_Core_DAO::executeQuery("INSERT INTO `civirule_rule_log` (`rule_id`, `contact_id`, `log_date`) VALUES ...", (Array:2)) #5 /home/sepg1/public_html/civicrm_extensions/org.civicoop.civirules/CRM/Civirules/Engine.php(30): CRM_Civirules_Engine::logRule(Object(CRM_Civirules_TriggerData_Post)) #6 /home/sepg1/public_html/civicrm_extensions/org.civicoop.civirules/CRM/Civirules/Trigger/Post.php(81): CRM_Civirules_Engine::triggerRule(Object(CRM_Civirules_Trigger_Post), Object(CRM_Civirules_TriggerData_Post)) #7 /home/sepg1/public_html/civicrm_extensions/org.civicoop.civirules/CRM/Civirules/Trigger/Post.php(66): CRM_Civirules_Trigger_Post->triggerTrigger("create", "EntityTag", "1", (Array:2)) #8 /home/sepg1/public_html/civicrm_extensions/org.civicoop.civirules/civirules.php(137): CRM_Civirules_Trigger_Post::post("create", "EntityTag", "1", (Array:2)) #9 /home/sepg1/public_html/sites/all/modules/civicrm/CRM/Utils/Hook.php(236): civirules_civicrm_post("create", "EntityTag", "1", (Array:2)) #10 /home/sepg1/public_html/sites/all/modules/civicrm/CRM/Utils/Hook/DrupalBase.php(85): CRM_Utils_Hook->runHooks((Array:57), "civicrm_post", 4, "create", "EntityTag", "1", (Array:2), NULL, NULL) #11 /home/sepg1/public_html/sites/all/modules/civicrm/CRM/Utils/Hook.php(325): CRM_Utils_Hook_DrupalBase->invoke(4, "create", "EntityTag", "1", (Array:2), NULL, NULL, "civicrm_post") #12 /home/sepg1/public_html/sites/all/modules/civicrm/CRM/Core/BAO/EntityTag.php(167): CRM_Utils_Hook::post("create", "EntityTag", "1", (Array:2)) #13 /home/sepg1/public_html/sites/all/modules/civicrm/api/v3/EntityTag.php(151): CRM_Core_BAO_EntityTag::addEntitiesToTag((Array:1), "1", "civicrm_contact", TRUE) #14 /home/sepg1/public_html/sites/all/modules/civicrm/api/v3/EntityTag.php(82): _civicrm_api3_entity_tag_common((Array:5), "add") #15 /home/sepg1/public_html/sites/all/modules/civicrm/Civi/API/Provider/MagicFunctionProvider.php(89): civicrm_api3_entity_tag_create((Array:5)) #16 /home/sepg1/public_html/sites/all/modules/civicrm/Civi/API/Kernel.php(96): Civi\API\Provider\MagicFunctionProvider->invoke((Array:9)) #17 /home/sepg1/public_html/sites/all/modules/civicrm/api/api.php(23): Civi\API\Kernel->run("entity_tag", "create", (Array:5), NULL) #18 /home/sepg1/public_html/sites/all/modules/civicrm/CRM/Utils/REST.php(404): civicrm_api("entity_tag", "create", (Array:5)) #19 /home/sepg1/public_html/sites/all/modules/civicrm/CRM/Utils/REST.php(641): CRM_Utils_REST::process((Array:3), (Array:3)) #20 [internal function](): CRM_Utils_REST::ajax() #21 /home/sepg1/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php(278): call_user_func((Array:2)) #22 /home/sepg1/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php(86): CRM_Core_Invoke::runItem((Array:12)) #23 /home/sepg1/public_html/sites/all/modules/civicrm/CRM/Core/Invoke.php(54): CRM_Core_Invoke::_invoke((Array:3)) #24 /home/sepg1/public_html/sites/all/modules/civicrm/drupal/civicrm.module(454): CRM_Core_Invoke::invoke((Array:3)) #25 [internal function](): civicrm_invoke("ajax", "rest") #26 /home/sepg1/public_html/includes/menu.inc(527): call_user_func_array("civicrm_invoke", (Array:2)) #27 /home/sepg1/public_html/index.php(21): menu_execute_active_handler() #28 {main}

**Comment by jaapjansma** [comment]
Hey @sgladstone, thanks for reporting this issue. I am not sure whether you could possibly fix this yourself or not. But it looks like the contact_id is not present in the TriggerData. This could be caused by the fact that the post hook is called and in this hook the data for the civirules engine is set, including a contact_id. Hope this could help you forward.

**Comment by sgladstone** [comment]
I updated the CiviRules extension to version 1.4 and I am no longer having this issue. (I also updated CiviCRM to 4.7.12)
