### ISSUE TITLE
add tags to civirules, allowing you to filter what you see on the rules page

### ISSUE THREAD

**Issue by ErikHommel** [CiviCooP/org.civicoop.civirules#98]

**Comment by JohnFF** [comment]
Hi @ErikHommel ,
I suggest something slightly different: Categories.
That way you could have tabs along the top of the Rules page, it'd be a kind of filter, but a bit firmer.
Do you think that may be a better alternative?

**Comment by ErikHommel** [comment]
Good idea @JohnFF, please go ahead :-) 
I will not implement now as I am working on the other solution and would not like to start over again and add it to the bill of my customer. But nice if you could and would....
